<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Introduktion till R - Icke-parametriska tester</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Introduktion till R</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html">
 <span class="menu-text">Hem</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../tutorials/index.html">
 <span class="menu-text">Tutorials</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html">
 <span class="menu-text">Om hemsidan</span></a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#icke-paramatriska-test" id="toc-icke-paramatriska-test" class="nav-link active" data-scroll-target="#icke-paramatriska-test">Icke-paramatriska test</a></li>
  <li><a href="#wilcoxons-test" id="toc-wilcoxons-test" class="nav-link" data-scroll-target="#wilcoxons-test">Wilcoxons test</a>
  <ul class="collapse">
  <li><a href="#läs-in-data" id="toc-läs-in-data" class="nav-link" data-scroll-target="#läs-in-data">Läs in data</a></li>
  <li><a href="#inspektera-data" id="toc-inspektera-data" class="nav-link" data-scroll-target="#inspektera-data">Inspektera data</a></li>
  <li><a href="#visualisera-datat-med-en-enkel-graf" id="toc-visualisera-datat-med-en-enkel-graf" class="nav-link" data-scroll-target="#visualisera-datat-med-en-enkel-graf">Visualisera datat med en enkel graf</a></li>
  <li><a href="#statistisk-modellering" id="toc-statistisk-modellering" class="nav-link" data-scroll-target="#statistisk-modellering">Statistisk modellering</a></li>
  <li><a href="#statistiska-resultat" id="toc-statistiska-resultat" class="nav-link" data-scroll-target="#statistiska-resultat">Statistiska resultat</a></li>
  <li><a href="#presentera-din-statistiska-analys" id="toc-presentera-din-statistiska-analys" class="nav-link" data-scroll-target="#presentera-din-statistiska-analys">Presentera din statistiska analys</a></li>
  </ul></li>
  <li><a href="#kruskal-wallis-test" id="toc-kruskal-wallis-test" class="nav-link" data-scroll-target="#kruskal-wallis-test">Kruskal Wallis test</a>
  <ul class="collapse">
  <li><a href="#läs-in-data-1" id="toc-läs-in-data-1" class="nav-link" data-scroll-target="#läs-in-data-1">Läs in data</a></li>
  <li><a href="#inspektera-data-1" id="toc-inspektera-data-1" class="nav-link" data-scroll-target="#inspektera-data-1">Inspektera data</a></li>
  <li><a href="#visualisera-datat-med-en-enkel-graf-1" id="toc-visualisera-datat-med-en-enkel-graf-1" class="nav-link" data-scroll-target="#visualisera-datat-med-en-enkel-graf-1">Visualisera datat med en enkel graf</a></li>
  <li><a href="#statistisk-modellering-1" id="toc-statistisk-modellering-1" class="nav-link" data-scroll-target="#statistisk-modellering-1">Statistisk modellering</a></li>
  <li><a href="#post-hoc-test" id="toc-post-hoc-test" class="nav-link" data-scroll-target="#post-hoc-test">Post-hoc test</a></li>
  <li><a href="#presentera-din-statistiska-analys-1" id="toc-presentera-din-statistiska-analys-1" class="nav-link" data-scroll-target="#presentera-din-statistiska-analys-1">Presentera din statistiska analys</a></li>
  </ul></li>
  <li><a href="#spearman-korrelation" id="toc-spearman-korrelation" class="nav-link" data-scroll-target="#spearman-korrelation">Spearman-korrelation</a>
  <ul class="collapse">
  <li><a href="#läs-in-data-2" id="toc-läs-in-data-2" class="nav-link" data-scroll-target="#läs-in-data-2">Läs in data</a></li>
  <li><a href="#inspektera-data-2" id="toc-inspektera-data-2" class="nav-link" data-scroll-target="#inspektera-data-2">Inspektera data</a></li>
  <li><a href="#visualisera-datat" id="toc-visualisera-datat" class="nav-link" data-scroll-target="#visualisera-datat">Visualisera datat</a></li>
  <li><a href="#statistisk-modellering-2" id="toc-statistisk-modellering-2" class="nav-link" data-scroll-target="#statistisk-modellering-2">Statistisk modellering</a></li>
  <li><a href="#resultat" id="toc-resultat" class="nav-link" data-scroll-target="#resultat">Resultat</a></li>
  <li><a href="#skillnad-i-resultat-mot-parametrisk-korrelation" id="toc-skillnad-i-resultat-mot-parametrisk-korrelation" class="nav-link" data-scroll-target="#skillnad-i-resultat-mot-parametrisk-korrelation">Skillnad i resultat mot parametrisk korrelation</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Icke-parametriska tester</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>De statistiska test vi behandlat nu är parametriska test, dvs de förutsätter att datan eller residualerna följer vissa fördelningar (exempelvis normalfördelning). Simuleringar visar också att parametriska modeller är väldigt robusta även mot avvikelser i normalförderade residualer (se exempelvis <a href="https://link.springer.com/article/10.3758/s13428-021-01587-5">Knief &amp; Forstmeier 2021</a>). Om residualerna dessutom avviker från normalfördelning kan det i många fall lösas genom transformeringar (se <a href="https://martin-lind.github.io/Introduktion-till-R/tutorials/transformations/">tidigare tutorial</a>) eller genom att använda generaliserade linjära modeller som kan specificera en annan errorstruktur (kommer presenteras i en framtida tutorial).</p>
<p>Ibland har man dock väldigt “konstiga” data, och speciellt om de samtidigt kommer från små dataset så kan man ibland behöva överväga icke-parametriska metoder.</p>
<p>Icke-parametriska metoder bygger på att värderna rankas, dvs är ett visst värde generellt högre eller lägre än de andra värderna. Testen använder sig inte av de exakta mätvärderna och tappar därmed mycket information (de är svaga test). Testen har svårare att upptäcka mönster som faktiskt finns och skall därmed bara användas i nödfall.</p>
<p><strong><em>Man kan överväga ickeparametriska metoder om:</em></strong></p>
<ul>
<li><p>Responsvariabeln är på <em>ordinalskala</em> (till exempel att arters täthet är skattad som ovanlig, vanlig, mycket vanlig), kategorierna är därmed ordnade men går inte att översätta till mätvärden</p></li>
<li><p>Responsvariabeln innehåller väldigt många nollvärden</p></li>
<li><p>Datasetet innehåller några kraftigt avvikande värden (<em>outliers</em>) som du litar på och behöver inkludera i datasetet</p></li>
<li><p>Datasetet är litet och residualerna är långt ifrån normalfördelade</p></li>
</ul>
<p>Icke-parametriska test skall ses som ett svagt test som används som en nödlösning i små och avvikande dataset. Data som uppfyller många av punkterna ovan kan analyseras med parametriska test om datasetet är stort nog.</p>
<section id="icke-paramatriska-test" class="level2">
<h2 class="anchored" data-anchor-id="icke-paramatriska-test">Icke-paramatriska test</h2>
<p>De icke-parametriska testen som oftast används är:</p>
<ul>
<li><p><a href="#wilcoxons-test">Wilcoxons test</a> - alternativ till t-test</p></li>
<li><p><a href="#kruskal-wallis-test">Kruskal Wallis test</a> - alternativ till envägs-ANOVA</p></li>
<li><p><a href="#spearman-korrelation">Spearman-korrelation</a> - alternativ till parametrisk korrelation</p></li>
</ul>
</section>
<section id="wilcoxons-test" class="level2">
<h2 class="anchored" data-anchor-id="wilcoxons-test">Wilcoxons test</h2>
<p>Wilcoxons test (kallas ibland Mann-Whitney U-test) används som ett icke-parametriskt alternativ till t-test</p>
<p>Vi vill undersöka om den sydliga kärrsnäppans häckningsframgång kan förbättras om man har predatorkontroll. Vi har därför inventerat antalet ungar hos honor i slumpvis utvalda bon i områden där man haft predatorkontroll, och områden där inga åtgärder gjorts.</p>
<section id="läs-in-data" class="level3">
<h3 class="anchored" data-anchor-id="läs-in-data">Läs in data</h3>
<p>Ladda ner följande fil <a href="data/dunlin.txt">dunlin.txt</a> (högerklicka, välj “spara länk som”) och spara filen på din hårddisk i en mapp med ett lämpligt namn.</p>
<p>Fortsätt med att läsa in datasetet och ge det ett namn, i det här fallet kallar vi det <code>dunlin_data.</code> En detaljerad beskrivning i hur man läser in filer finns i vår tidigare tutorial <a href="https://martin-lind.github.io/Introduktion-till-R/tutorials/read-data/#l%C3%A4s-in-filen">Läsa in data i R</a>.</p>
<p><strong>Glöm inte att dokumentera din kod i ett script,</strong> med kommentarer som förklarar vad du gör! <a href="https://martin-lind.github.io/Introduktion-till-R/tutorials/use-R/#anv%C3%A4nda-scriptfiler">Se vår tutorial om script</a> om du behöver påminnelse om hur man skapar och använder script.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>dunlin_data <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">"data/dunlin.txt"</span>,</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>                           <span class="at">header=</span>T,</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>                           <span class="at">sep=</span><span class="st">"</span><span class="sc">\t</span><span class="st">"</span>,</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>                           <span class="at">dec=</span><span class="st">","</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="inspektera-data" class="level3">
<h3 class="anchored" data-anchor-id="inspektera-data">Inspektera data</h3>
<p>Börja med att titta på datans struktur med <code>str()</code>.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(dunlin_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   14 obs. of  2 variables:
 $ offspring: int  0 0 1 0 2 0 0 3 4 3 ...
 $ treatment: chr  "control" "control" "control" "control" ...</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dunlin_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  offspring treatment
1         0   control
2         0   control
3         1   control
4         0   control
5         2   control
6         0   control</code></pre>
</div>
</div>
<p>Det ser ut som om vi har många nollor i datasetet. Låt oss se på ett histogram:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(dunlin_data<span class="sc">$</span>offspring)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>De flesta honor verkar inte ha fått några ungar. Låt oss se på en QQ-plot som vi även använde i vår tutorial om t-test</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(dunlin_data<span class="sc">$</span>offspring)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(dunlin_data<span class="sc">$</span>offspring)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Vi vill att våra värden skall följa en diagonal, men det gör de inte. Vi har ett dataset som inte uppfyller t-testets krav på normalfördelade data, och vi kan inte få en bättre fördelning genom att transformera då datasetet mest består av nollvärden som kommer fortsätta att vara nollvärden.</p>
</section>
<section id="visualisera-datat-med-en-enkel-graf" class="level3">
<h3 class="anchored" data-anchor-id="visualisera-datat-med-en-enkel-graf">Visualisera datat med en enkel graf</h3>
<p>Vi gör en enkel graf med <code>boxplot()</code></p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(offspring<span class="sc">~</span>treatment, </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">data =</span> dunlin_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Hur tolkar du grafen? Ser det ut som att antalet avkomma skiljer sig åt beroende på om det är predatorkontroll eller ej?</p>
</section>
<section id="statistisk-modellering" class="level3">
<h3 class="anchored" data-anchor-id="statistisk-modellering">Statistisk modellering</h3>
<p>Vi vill nu göra ett Wilcoxons test för att undersöka om vår responsvariabel (beroende variabel) <em>offspring</em> beror av vår förklarande variabel (oberoende variabel) <em>treatment</em>, med andra ord om antalet avkomma beror av huruvida området haft predatorkontroll eller ej</p>
<p>Vi specificerar en modell med hjälp av funktionen <code>wilcox.test()</code> och väljer att spara resultatet i ett objekt som vi kallar <code>m.dunlin</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>m.dunlin<span class="ot">&lt;-</span><span class="fu">wilcox.test</span>(offspring<span class="sc">~</span>treatment,</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">data=</span>dunlin_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in wilcox.test.default(x = DATA[[1L]], y = DATA[[2L]], ...): cannot
compute exact p-value with ties</code></pre>
</div>
</div>
<p>Vi får en varning <code>Warning: cannot compute exact p-value with ties</code>. Det betyder att testet upptäcker att vissa värden är identiska (vi har många nollor) och att p-värderna därmed inte går att lita på fullt ut. Det är dock oftast inga problem.</p>
</section>
<section id="statistiska-resultat" class="level3">
<h3 class="anchored" data-anchor-id="statistiska-resultat">Statistiska resultat</h3>
<p>Vi tittar på resultatet genom att skriva in modellens namn och köra den</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>m.dunlin</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon rank sum test with continuity correction

data:  offspring by treatment
W = 9.5, p-value = 0.04704
alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
</div>
<p>Vi kan nu inspektera resultatet. Vi får teststatistika (W-värde) samt ett p-värde. Vi får inga frigetsgrader i det här testet.</p>
<p>Eftersom vårt p-värde är mindre än 0.05 säger vi att antalet avkommor skiljer sig åt beroende på behandling. Stämmer det om du tittar på din boxplot?</p>
</section>
<section id="presentera-din-statistiska-analys" class="level3">
<h3 class="anchored" data-anchor-id="presentera-din-statistiska-analys">Presentera din statistiska analys</h3>
<p>Den sydliga kärrsnäppan fårt fler avkommor om man tillämpar predatorkontroll än i områden utan predatorkontroll (Wilcoxons test, W = 9.5, p = 0.047).</p>
</section>
</section>
<section id="kruskal-wallis-test" class="level2">
<h2 class="anchored" data-anchor-id="kruskal-wallis-test">Kruskal Wallis test</h2>
<p>Kruskal Wallis test är en ickeparametrisk ersättning till envägs ANOVA. Det är ett svagare och mindre flexibelt test än en vanlig envägs ANOVA och skall bara användas i nödfall.</p>
<p>Vi vill undersöka om täckningsgraden av blåbär skiljer sig åt i tre skogar. Täckningsgraden har skattats enligt Braun-Blanquet-skalan med fem nivåer (1-5) där täckningsgraden ökar från 1 -&gt; 5. Data är därmed ordnade (1 är lägre än 5) men på ordinalskala (kategorierna är inga mätvärden).</p>
<section id="läs-in-data-1" class="level3">
<h3 class="anchored" data-anchor-id="läs-in-data-1">Läs in data</h3>
<p>Ladda ner följande fil <a href="data/cover.txt">cover.txt</a> (högerklicka, välj “spara länk som”) och spara filen på din hårddisk i en mapp med ett lämpligt namn.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>cover_data <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">"data/cover.txt"</span>,</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>                           <span class="at">header=</span>T,</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>                           <span class="at">sep=</span><span class="st">"</span><span class="sc">\t</span><span class="st">"</span>,</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>                           <span class="at">dec=</span><span class="st">","</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="inspektera-data-1" class="level3">
<h3 class="anchored" data-anchor-id="inspektera-data-1">Inspektera data</h3>
<p>Börja med att titta på datans struktur med <code>str()</code>.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(cover_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   30 obs. of  2 variables:
 $ Cover.cathegory: int  1 2 1 4 3 2 3 1 1 2 ...
 $ Forest         : chr  "A" "A" "A" "A" ...</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(cover_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  Cover.cathegory Forest
1               1      A
2               2      A
3               1      A
4               4      A
5               3      A
6               2      A</code></pre>
</div>
</div>
<p>Låt oss se på ett histogram</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(cover_data<span class="sc">$</span>Cover.cathegory)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Vi ser att våra data ser väldigt jämna ut, och kanske inte är normalfördelade. <strong>Dessutom vet vi att det är <em>ordinaldata</em></strong>, dvs vår responsvariabel är inte mätvärden utan i ordnade kategorier. Bara det senare faktumet gör att vi inte skall använda oss av en vanlig envägs-ANOVA.</p>
</section>
<section id="visualisera-datat-med-en-enkel-graf-1" class="level3">
<h3 class="anchored" data-anchor-id="visualisera-datat-med-en-enkel-graf-1">Visualisera datat med en enkel graf</h3>
<p>Vi gör en enkel graf med <code>boxplot()</code></p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(Cover.cathegory<span class="sc">~</span>Forest, </span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">data =</span> cover_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Hur tolkar du grafen? Ser det ut som att blåbärens täckningsgrad skiljer sig åt mellan skogarna?</p>
</section>
<section id="statistisk-modellering-1" class="level3">
<h3 class="anchored" data-anchor-id="statistisk-modellering-1">Statistisk modellering</h3>
<p>Vi vill nu göra ett Kruskal Wallis test för att undersöka om vår responsvariabel (beroende variabel) <em>Cover.cathegory</em> beror av vår förklarande variabel (oberoende variabel) <em>Forest</em></p>
<p>Vi specificerar en modell med hjälp av funktionen <code>kruskal.test()</code> och väljer att spara resultatet i ett objekt som vi kallar <code>m.cover</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>m.cover<span class="ot">&lt;-</span><span class="fu">kruskal.test</span>(Cover.cathegory<span class="sc">~</span>Forest,</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">data=</span>cover_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>m.cover</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Kruskal-Wallis rank sum test

data:  Cover.cathegory by Forest
Kruskal-Wallis chi-squared = 11.883, df = 2, p-value = 0.002629</code></pre>
</div>
</div>
</section>
<section id="post-hoc-test" class="level3">
<h3 class="anchored" data-anchor-id="post-hoc-test">Post-hoc test</h3>
<p>Vi har en signifikant efekt av Forest, d.v.s. täckningsgraden för blåbär skiljer sig åt mellan de olika skogarna. Men vilka skogar skiljer sig åt? Vi behöver göra ett post-hoc test! Om vi inte hade haft en signifikant effekt skall vi däremot inte göra ett post-hoc test.</p>
<p>När man gör ett posthoc-test på en icke-parametrisk envägs-ANOVA använder man sig av <em>Dunn Test</em>, vilket finns tillgängligt i paketet <strong>dunn.test</strong>. Om du inte sedan tidigare har paketet installerat så gör du det med koden <code>install.packages("dunn.test")</code>. Innan du använder paketet behöver du läsa in det i din session i R genom funktionen <code>library()</code></p>
<p>När vi läst in paketet använder vi oss av funktionen <code>dunn.test()</code>. Först anger vi vår responsvariabel, och det gör vi enligt formeln <strong><code>Datatset$Variabel</code></strong>, vilket i vårat fall blir <code>cover_data$Cover.cathegory</code>. Efter det anger vi vår förklarande faktor på samma sätt, vilket blir <code>cover_data$Forest</code>, och slutligen anger vi metoden för att korrigera p-värden för multipla test. Vanligt är att använda sig av <em>Holm’s metod</em>, anges med <code>method="holm"</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dunn.test)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="fu">dunn.test</span>(cover_data<span class="sc">$</span>Cover.cathegory,cover_data<span class="sc">$</span>Forest,<span class="at">method=</span><span class="st">"holm"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Kruskal-Wallis rank sum test

data: x and group
Kruskal-Wallis chi-squared = 11.8825, df = 2, p-value = 0

                           Comparison of x by group                            
                                    (Holm)                                     
Col Mean-|
Row Mean |          A          B
---------+----------------------
       B |  -3.414601
         |    0.0010*
         |
       C |  -1.298327   2.116273
         |     0.0971     0.0343

alpha = 0.05
Reject Ho if p &lt;= alpha/2</code></pre>
</div>
</div>
<p>Vi får en tabell med jämförelser. Om vi börjar med <em>Kolumn A</em> och <em>Rad B</em> får vi p-värdet <code>0.0010.</code> Det betyder att täckningsgraden för blåbär skiljer sig åt mellan skogarna A och B.</p>
<p><em>Kolumn A</em> och <em>rad C</em> ger ett p-värde på <code>0.0971.</code> Täckningsgraden skiljer sig alltså <strong>inte</strong> åt mellan skogarna A och C.</p>
<p><em>Kolumn B</em> och <em>rad C</em> ger ett p-värde på <code>0.0343.</code> Täckningsgraden av blåbär skiljer sig åt mellan skogarna B och C.</p>
</section>
<section id="presentera-din-statistiska-analys-1" class="level3">
<h3 class="anchored" data-anchor-id="presentera-din-statistiska-analys-1">Presentera din statistiska analys</h3>
<p>Täckningsgraden av blåbär skiljer sig åt mellan de olika skogarna (Kruskal Wallis test, <span class="math inline">\(\chi\)</span> <sup>2</sup> = 11.883,d.f. = 2, p = 0.003). Post-hoc analys visar att täckningsgraden är högre i skog B än i skog A (Dunnet’s test, p = 0.001) och C (Dunnet’s test, p = 0.034). Täckningsgraden skiljer sig inte åt mellan skog A och C (Dunnet’s test, p = 0.097).</p>
</section>
</section>
<section id="spearman-korrelation" class="level2">
<h2 class="anchored" data-anchor-id="spearman-korrelation">Spearman-korrelation</h2>
<p>En vanlig korrelationsanalys som vi tidigare gjort kräver att datat är normalfördelat, och även om det kan hantera mindre avvikelser från det så har man ibland data som inte alls är normalfördelat. Då använder man sig av Spearman-korrelation, som är en icke-parametrisk korrelationsanalys som baserar sig på datats rank och inte på de faktiska värderna. Därmed är det mindre kraftfullt än en parametrisk korrelation, men kan hantera avvikande data.</p>
<section id="läs-in-data-2" class="level3">
<h3 class="anchored" data-anchor-id="läs-in-data-2">Läs in data</h3>
<p>Ladda ner följande fil <a href="data/spearman.txt">spearman.txt</a> (högerklicka, välj “spara länk som”) och spara filen på din hårddisk i en mapp med ett lämpligt namn.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>spearman_data <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">"data/spearman.txt"</span>,</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>                           <span class="at">header=</span>T,</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>                           <span class="at">sep=</span><span class="st">"</span><span class="sc">\t</span><span class="st">"</span>,</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>                           <span class="at">dec=</span><span class="st">","</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="inspektera-data-2" class="level3">
<h3 class="anchored" data-anchor-id="inspektera-data-2">Inspektera data</h3>
<p>Börja med att titta på datans struktur med <code>str()</code>.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(spearman_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   20 obs. of  2 variables:
 $ A: num  0.664 0.941 0.768 0.912 0.925 ...
 $ B: num  0.778 0.61 0.578 0.974 0.656 ...</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(spearman_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>          A         B
1 0.6640666 0.7782157
2 0.9413902 0.6104316
3 0.7678628 0.5783860
4 0.9118415 0.9743616
5 0.9249759 0.6561892
6 0.7146678 0.9645745</code></pre>
</div>
</div>
<p>Låt oss se på ett histogram över variabel <code>A</code></p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(spearman_data<span class="sc">$</span>A)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Det ser verkligen inte ut som en normalfördelning. Hur ser variabel <code>B</code> ut?</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(spearman_data<span class="sc">$</span>B)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Variabel B ser lite bättre ut, men det är som helhet ett dataset som avviker kraftigt från normalfördelningen. Att analysera det med en parametrisk korrelation bryter mot dess antagande om normalfördelning, och då kan vi inte lite på en sådan korrelations resultat.</p>
</section>
<section id="visualisera-datat" class="level3">
<h3 class="anchored" data-anchor-id="visualisera-datat">Visualisera datat</h3>
<p>Som vanligt gör vi en graf innan vi börjar med vår statistiska modellering</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(B <span class="sc">~</span> A, <span class="at">data =</span> spearman_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Vi ser i grafen att det eventuellt är en positiv korrelation mellan A och B, men också att speciellt variabel A har en underlig fördelning med mest låga eller höga värden, vilket vi också såg i vårt histogram.</p>
</section>
<section id="statistisk-modellering-2" class="level3">
<h3 class="anchored" data-anchor-id="statistisk-modellering-2">Statistisk modellering</h3>
<p>Vi gör nu en icke-parametrisk korrelation, och den har stora likheter med korrelationen vi tidigare gjort. Vi använder oss fortfarande av funktionen <code>cor.test()</code>, den enda skillnaden är att vi anger <code>method = "s"</code> (står för Spearman) där vi tidigare angett <code>"p"</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>m.spearman <span class="ot">&lt;-</span><span class="fu">cor.test</span>(spearman_data<span class="sc">$</span>A, spearman_data<span class="sc">$</span>B, <span class="at">method =</span> <span class="st">"s"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="resultat" class="level3">
<h3 class="anchored" data-anchor-id="resultat">Resultat</h3>
<p>Vi skriver in modellens namn och tittar på resultatet</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>m.spearman</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Spearman's rank correlation rho

data:  spearman_data$A and spearman_data$B
S = 782, p-value = 0.07226
alternative hypothesis: true rho is not equal to 0
sample estimates:
      rho 
0.4120301 </code></pre>
</div>
</div>
<p>Vi ser att A och B inte är signifikant korrelerade eftersom p-värdet är <code>0.07226</code>. Vi får också en korrelationskoefficient (kallas <code>rho</code>) på 0.412.</p>
</section>
<section id="skillnad-i-resultat-mot-parametrisk-korrelation" class="level3">
<h3 class="anchored" data-anchor-id="skillnad-i-resultat-mot-parametrisk-korrelation">Skillnad i resultat mot parametrisk korrelation</h3>
<p>Vad hade hänt om vi analyserat datat med en parametrisk korrelation? Vi testar, genom att använda <code>method = "p"</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>m.pearson <span class="ot">&lt;-</span><span class="fu">cor.test</span>(spearman_data<span class="sc">$</span>A, spearman_data<span class="sc">$</span>B, <span class="at">method =</span> <span class="st">"p"</span>)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>m.pearson</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  spearman_data$A and spearman_data$B
t = 2.6376, df = 18, p-value = 0.01672
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.1115075 0.7866933
sample estimates:
      cor 
0.5279756 </code></pre>
</div>
</div>
<p>Vi får nu ett signifikant p-värde, och om vi inte hade vetat att våra data inte var normalfördelade hade vi dragit den felaktiga slutsatsen att A och B var positivt korrelerade. Men eftersom datat inte uppfyller kraven för att få göra en parametrisk korrelation så kan vi inte lite på p-värderna från en sådan korrelation.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>