<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Ordination with NMDS – Introduktion till R</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-158031087360bce0ff56dc785ce39e06.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link href="../../site_libs/htmltools-fill-0.5.9/fill.css" rel="stylesheet">
<script src="../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<script src="../../site_libs/plotly-binding-4.12.0/plotly.js"></script>
<script src="../../site_libs/typedarray-0.1/typedarray.min.js"></script>
<script src="../../site_libs/jquery-3.5.1/jquery.min.js"></script>
<link href="../../site_libs/crosstalk-1.2.2/css/crosstalk.min.css" rel="stylesheet">
<script src="../../site_libs/crosstalk-1.2.2/js/crosstalk.min.js"></script>
<link href="../../site_libs/plotly-htmlwidgets-css-2.25.2/plotly-htmlwidgets.css" rel="stylesheet">
<script src="../../site_libs/plotly-main-2.25.2/plotly-latest.min.js"></script>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Introduktion till R</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Hem</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../tutorials/index.html"> 
<span class="menu-text">Tutorials</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">Om hemsidan</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#the-multivariate-ordination-analysis" id="toc-the-multivariate-ordination-analysis" class="nav-link active" data-scroll-target="#the-multivariate-ordination-analysis">The multivariate ordination analysis</a></li>
  <li><a href="#illustrating-an-ordination" id="toc-illustrating-an-ordination" class="nav-link" data-scroll-target="#illustrating-an-ordination">Illustrating an ordination</a></li>
  <li><a href="#different-multivariate-analyses" id="toc-different-multivariate-analyses" class="nav-link" data-scroll-target="#different-multivariate-analyses">Different multivariate analyses</a></li>
  <li><a href="#nmds---non-metric-multidimensional-scaling" id="toc-nmds---non-metric-multidimensional-scaling" class="nav-link" data-scroll-target="#nmds---non-metric-multidimensional-scaling">NMDS - Non-Metric Multidimensional Scaling</a></li>
  <li><a href="#load-the-data" id="toc-load-the-data" class="nav-link" data-scroll-target="#load-the-data">Load the data</a>
  <ul class="collapse">
  <li><a href="#inspect-the-data" id="toc-inspect-the-data" class="nav-link" data-scroll-target="#inspect-the-data">Inspect the data</a></li>
  </ul></li>
  <li><a href="#create-a-community-matrix" id="toc-create-a-community-matrix" class="nav-link" data-scroll-target="#create-a-community-matrix">Create a community matrix</a></li>
  <li><a href="#run-an-nmds" id="toc-run-an-nmds" class="nav-link" data-scroll-target="#run-an-nmds">Run an NMDS</a>
  <ul class="collapse">
  <li><a href="#stress-values" id="toc-stress-values" class="nav-link" data-scroll-target="#stress-values">Stress values</a></li>
  </ul></li>
  <li><a href="#simple-figure" id="toc-simple-figure" class="nav-link" data-scroll-target="#simple-figure">Simple figure</a></li>
  <li><a href="#complete-figure" id="toc-complete-figure" class="nav-link" data-scroll-target="#complete-figure">Complete figure</a>
  <ul class="collapse">
  <li><a href="#what-should-be-included-in-the-graph" id="toc-what-should-be-included-in-the-graph" class="nav-link" data-scroll-target="#what-should-be-included-in-the-graph">What should be included in the graph?</a></li>
  </ul></li>
  <li><a href="#statistical-analysis---do-our-habitats-differ" id="toc-statistical-analysis---do-our-habitats-differ" class="nav-link" data-scroll-target="#statistical-analysis---do-our-habitats-differ">Statistical analysis - do our habitats differ?</a>
  <ul class="collapse">
  <li><a href="#post-hoc-test-on-the-habitats" id="toc-post-hoc-test-on-the-habitats" class="nav-link" data-scroll-target="#post-hoc-test-on-the-habitats">Post-hoc test on the habitats</a></li>
  <li><a href="#evaluate-your-model" id="toc-evaluate-your-model" class="nav-link" data-scroll-target="#evaluate-your-model">Evaluate your model</a></li>
  </ul></li>
  <li><a href="#environmental-variables" id="toc-environmental-variables" class="nav-link" data-scroll-target="#environmental-variables">Environmental variables</a>
  <ul class="collapse">
  <li><a href="#figure-with-environmental-variables" id="toc-figure-with-environmental-variables" class="nav-link" data-scroll-target="#figure-with-environmental-variables">Figure with environmental variables</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Ordination with NMDS</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Up to now, we have always had a single response variable in each analysis — it might be plant height, the number of chicks in a chaffinch nest, or the pH value of lakes. Such models are called <strong>univariate</strong>, since they only have one dependent variable (response variable) per analysis. But sometimes you might be interested in many response variables at once? Say you have looked at the occurrence of every plant species in two different environments, and found around seventy species. You could test species by species whether abundance differs between the two environments, but that becomes a huge number of univariate tests. Wouldn’t it be better to instead look at whether the <strong>plant community</strong> as a whole differs between the two environments?</p>
<p>These are exactly the kinds of questions that <strong>multivariate methods</strong> are useful for. Multivariate methods have more than one dependent variable (response variable), where all response variables are analyzed together in the same analysis.</p>
<p>The most common type of multivariate method used by ecologists is <strong>ordination</strong>. The method is used in genetics, where one can measure gene expression of tens of thousands of genes and wants to know whether gene expression differs between treatments, but also when one has measured dozens of morphological traits of individuals and wants to see whether they differ in shape. What we will focus on here, however, is how ordination is used in the analysis of biodiversity data. This can be which species you observed during surveys, but a newer research field that also uses similar methods is the analysis of microbiome data and metabarcoding studies with eDNA.</p>
<section id="the-multivariate-ordination-analysis" class="level3">
<h3 class="anchored" data-anchor-id="the-multivariate-ordination-analysis">The multivariate ordination analysis</h3>
<p>All our previous analyses have had one response variable, which we plotted on the y-axis, and with our predictor on the x-axis we got a graph in two dimensions. But what do we do if we have yet another response variable? Can we have an additional axis? Yes, in principle we can, if we make the graph in three dimensions (a 3D graph). But after that it gets difficult — how do you visualize 4 dimensions? Can you picture it? If we have measured the abundance of 50 species, we get 50 axes — you can’t even imagine what such a graph would look like! What should we do?</p>
<p>This is where ordination comes in. All your data points lie in the multivariate space, which has as many dimensions as you have response variables. But your data is not scattered completely at random in this space. If, for example, you have looked at species occurrence in replicated quadrats in a spruce forest and in a pine forest, the species composition across all your quadrats in the spruce forest will likely resemble each other, and the same applies in the pine forest. What the multivariate analysis does is try to reduce your multivariate data so that it can be illustrated in two dimensions. It first searches for the straight line through your multivariate space that explains the most variation in your dataset, and that becomes your first axis. It then finds a line that is perpendicular to your first axis and that explains the most of the remaining variation in your data. That becomes your second axis. Now we have two axes, and we can make a figure in two dimensions. Note that these axes do not correspond to any of the axes (dimensions) you fed into your analysis — instead they correspond to combinations of your original axes.</p>
</section>
<section id="illustrating-an-ordination" class="level3">
<h3 class="anchored" data-anchor-id="illustrating-an-ordination">Illustrating an ordination</h3>
<p>The figure below shows multivariate data in 3 dimensions (think of three species called X, Y and Z), where each dot corresponds to a quadrat with a certain number of individuals of species X, Y and Z.</p>
<ol type="1">
<li><p>You can rotate the graph with your mouse. Rotate it until you see the dimension with the most variation — that should be your first axis.</p></li>
<li><p>Then click “Add Axis 1” — that is the first axis of your ordination, which explains the most variation.</p></li>
<li><p>Then add Axis 2 with the corresponding button — this is an axis that is perpendicular to axis 1 and explains the second-most variation.</p></li>
<li><p>Rotate the figure so that Axis 1 and Axis 2 form a flat cross facing you (roughly as if you had placed the cross on a floor and were looking straight down at it). That corresponds to your ordination in 2 dimensions!</p></li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div class="plotly html-widget html-fill-item" id="htmlwidget-bbbdcf888a2a729dbcc9" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-bbbdcf888a2a729dbcc9">{"x":{"visdat":{"44ae598cbb1f":["function () ","plotlyVisDat"],"44ae26511e27":["function () ","data"],"44ae1792a618":["function () ","data"],"44ae1cd67dbf":["function () ","data"]},"cur_data":"44ae1cd67dbf","attrs":{"44ae26511e27":{"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"x":{},"y":{},"z":{},"type":"scatter3d","mode":"markers","marker":{"size":3},"name":"Data","inherit":true},"44ae1792a618":{"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"x":{},"y":{},"z":{},"type":"scatter3d","mode":"lines","line":{"width":6,"color":"red"},"name":"Axel 1","visible":false,"inherit":true},"44ae1cd67dbf":{"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"x":{},"y":{},"z":{},"type":"scatter3d","mode":"lines","line":{"width":6,"color":"blue"},"name":"Axel 2","visible":false,"inherit":true}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"updatemenus":[{"type":"buttons","direction":"right","x":0.10000000000000001,"y":1.1000000000000001,"buttons":[{"label":"Show Data","method":"update","args":[{"visible":[true,false,false]}]},{"label":"Add axis 1","method":"update","args":[{"visible":[true,true,false]}]},{"label":"Add axis 2","method":"update","args":[{"visible":[true,true,true]}]}]}],"scene":{"camera":{"eye":{"x":-0.5,"y":1.8,"z":0.59999999999999998}},"xaxis":{"title":"x"},"yaxis":{"title":"y"},"zaxis":{"title":"z"}},"hovermode":"closest","showlegend":true},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"x":[-0.5604756465522126,-0.23017748948327998,1.558708314149124,0.070508391424575989,0.12928773516094624,1.7150649868832812,0.46091620598920241,-1.2650612346065337,-0.68685285189352596,-0.44566197009995812,1.2240817974394618,0.35981382705736381,0.40077145059405211,0.11068271594511968,-0.55584113475407493,1.7869131368030782,0.49785047822923945,-1.9666171566296382,0.70135590156368544,-0.47279140772793404,-1.0678237059868452,-0.21797491465829505,-1.0260044483072397,-0.72889122929114003,-0.6250392678492569,-1.6866933107424134,0.83778704449452468,0.15337311783651522,-1.1381369370119476,1.2538149210699268,0.42646422147681357,-0.29507148299227121,0.89512566104502245,0.87813348753304221,0.82158108163748722,0.688640254100091,0.55391765353758882,-0.061911710576721679,-0.30596266373991676,-0.38047100101238263,-0.6947069789205127,-0.20791727801959878,-1.2653963515682645,2.1689559653385126,1.2079619983049905,-1.1231085832033496,-0.40288483529907598,-0.46665535362321875,0.77996511833631788,-0.083369066471829248,0.25331851399475486,-0.028546755348703028,-0.042870457291316069,1.3686022840144578,-0.22577098565926762,1.5164706044295397,-1.5487528042302212,0.58461374963606905,0.12385424384461378,0.21594156874397266,0.37963948275988207,-0.50232345310930226,-0.3332073836694201,-1.0185753831070885,-1.0717912264755773,0.303528641404258,0.44820977862942618,0.053004226730504138,0.92226746787973757,2.0500846856271444,-0.49103116605653524,-2.3091688756408129,1.0057385244622568,-0.7092007625823924,-0.68800861646735789,1.0255713696966988,-0.28477300705100878,-1.2207177122545354,0.18130347974915023,-0.13889136243904462,0.0057641858998869339,0.38528040112633055,-0.37066003179240942,0.64437654851883319,-0.22048656181875062,0.33178196391569692,1.096839013149348,0.43518149083380292,-0.32593158553122681,1.148807618451094,0.99350385596211943,0.54839695950806977,0.23873173511144125,-0.62790607603937143,1.3606524485300073,-0.60025958714712668,2.1873329930165775,1.5326106261851893,-0.23570035910047693,-1.0264209003067806],"y":[-0.80358379909142053,-0.055700137008359241,1.1236207120881125,-0.11736458655920574,-0.37237909550375087,1.3495381271021649,-0.023719269937175935,-1.8460199559792954,-0.739595541658702,0.1029687284504166,0.69159195664737361,0.59183322275840777,-0.48832419366934032,0.060765189993826033,-0.18496930583152882,1.5801071905258199,0.45111847965786328,-1.893646729456399,0.13623254823415726,-0.8902975214848039,-0.7954356662394132,-0.64811723881903716,-1.0660822804961261,-0.71115907953203572,0.42189958833669816,-1.6753295994416599,0.78792292173804823,0.16167891905106757,-1.3914378666746225,0.96739789379414209,1.0634468063931253,-0.010305159854209656,0.73671698983248801,0.49125837385662141,-0.36935874546026792,1.1165808099871606,-0.28718591263233989,0.32044438697729,0.70978165361680823,-1.0263233812958057,-0.2048734154490548,-0.29743256711691307,-1.7983891608273557,0.97783094537993442,0.16560151185669569,-1.1639401276478312,-1.0531856607372108,-0.02936589641066123,1.6740265649318902,-0.71021049119505297,0.59652423493339279,0.36168371622149259,0.13180492364200597,0.59069352307306244,-0.24034309184274344,1.0729788159585085,-0.95750747677393711,0.28147162165694067,0.58757008841850134,-0.014537173888328786,0.83006731899757158,-0.92644726582047476,-0.89664352931459224,0.80565966098553143,-1.0658617752606778,0.39193670889376409,0.67685265992046517,-0.19948693146996843,0.99624499646059472,1.8245500121942586,-0.50051518666607497,-1.8146885837499926,0.78755719270057345,0.49686533944217659,-0.92107494131030054,0.27245896222002719,-0.20892420605526763,-0.82133379508205984,0.3633045232544117,-0.34029575630678854,-0.52705171826568598,0.93981690894580949,-0.4713532194107049,0.082744807488379479,-0.2945290339255488,0.16683762395828144,1.4324313553762988,0.39051383876564055,0.11628162416727927,0.66940008617474489,0.90202573956049625,0.27637461186103851,0.2382771521759387,-0.95000653982026795,0.43312119216001987,0.5183990226562819,2.0502208062494707,0.60045282013567958,-0.49414324562059192,-1.4138767625440798],"z":[1.0602424908931796,0.55782778457762294,0.3096954150999518,0.34206060129609439,-0.030812377727831519,0.21454760800320205,-0.15672753494936728,-0.37603326423923383,0.70390597021919266,-0.2807356661278243,0.4641859299393109,0.12420066150070552,0.96312092264049709,-0.22092011449797799,-0.71868335082359747,1.2572728774453881,-0.10699191323538199,-0.77674754444783622,-0.3083283731300509,-0.61166430857742404,-0.5822678927705921,0.39444062289982779,0.36174652946007713,0.20269628613183471,-0.62091815897326419,-0.31087280684640839,-0.16978158611418717,-0.3304261975840676,0.29068814098487294,-0.17110819690505147,0.87184505156670133,-0.1896039905227985,0.33381714688737302,-0.077574620760252011,0.23440381957518924,-0.64916218209872356,0.27165190637213271,0.082402031080684141,-0.20376365587431089,-0.2731067296448253,-0.68020245025254078,-0.26582822804615591,0.65484890738724977,0.22247688872240345,0.46477474840538735,0.73880865753213809,0.064025837907221023,-0.90443825979910786,-0.44461012794843924,0.41410860357504031,-0.24009944931752714,-0.4037166743156908,-0.23293532280248946,0.55234140865492076,0.75847182029610216,0.39205910135777533,0.053275588992829137,0.52324244614623561,-0.17116385235631384,-0.65411906490681415,-0.31975911309559046,-0.21816277337774589,0.12596658334043123,-0.1008862510157934,0.93040240625596171,0.80797383752588448,-0.045526390825898683,-0.79191550497257601,-0.032129697034181282,0.52228095069194191,0.32714547500527286,-0.12891387845327312,0.60875681912918855,-1.2012971580235829,0.35713969697608877,0.20776938796873007,0.0076921083717037264,-0.32668312901578245,0.19574376538350435,0.044980537085584221,-0.67273994036318219,0.27894311026614343,0.14908923410184466,0.16453901937379156,0.03718768479162967,0.18285901745459571,0.22919983424228541,0.92085967677595226,-0.30737546948253508,0.45761647531545235,0.81033614264745735,0.71837660788418289,0.62051427709311757,-0.3176850766033838,1.5516312317634124,-0.42229906490535646,1.4120261769868789,-0.089281875963464929,0.04088458731305783,0.5359098640944413],"type":"scatter3d","mode":"markers","marker":{"color":"rgba(31,119,180,1)","size":3,"line":{"color":"rgba(31,119,180,1)"}},"name":"Data","error_y":{"color":"rgba(31,119,180,1)"},"error_x":{"color":"rgba(31,119,180,1)"},"line":{"color":"rgba(31,119,180,1)"},"frame":null},{"x":[-2.3386246196584719,2.7991160313618506],"y":[-2.267773022324572,2.5681240233375968],"z":[-1.1386885055046718,1.4810368862880467],"type":"scatter3d","mode":"lines","line":{"color":"red","width":6},"name":"Axel 1","visible":false,"marker":{"color":"rgba(255,127,14,1)","line":{"color":"rgba(255,127,14,1)"}},"error_y":{"color":"rgba(255,127,14,1)"},"error_x":{"color":"rgba(255,127,14,1)"},"frame":null},{"x":[-0.16366821621512928,0.36591649973577933],"y":[-0.81358949654674007,0.92090063465987892],"z":[2.1342491076420624,-2.10615130200945],"type":"scatter3d","mode":"lines","line":{"color":"blue","width":6},"name":"Axel 2","visible":false,"marker":{"color":"rgba(44,160,44,1)","line":{"color":"rgba(44,160,44,1)"}},"error_y":{"color":"rgba(44,160,44,1)"},"error_x":{"color":"rgba(44,160,44,1)"},"frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<p>The names of the two axes depend on which type of ordination you have done (see below). If you do a PCA they are called PC1 and PC2, if you do an NMDS they are called NMDS1 and NMDS2, and so on. If you do a parametric analysis (such as PCA) you can find out how much variation is explained by each new axis, or something called an eigenvalue, whereas for non-parametric analyses you instead look at the analysis’s stress value (see below) to know whether your multivariate dataset can be visualized well in two dimensions.</p>
</section>
<section id="different-multivariate-analyses" class="level3">
<h3 class="anchored" data-anchor-id="different-multivariate-analyses">Different multivariate analyses</h3>
<p>Below we go through the most common multivariate analysis methods. The choice of method depends above all on whether the data is normally distributed, which is often determined by whether you have a lot of zeros in your dataset (which is common if you have surveyed species — you get zeros when species are absent from certain plots). For more general information on distributions, see our earlier tutorials on <a href="https://martin-lind.github.io/Introduktion-till-R/tutorials/transformations/">transformations</a> and <a href="https://martin-lind.github.io/Introduktion-till-R/tutorials/non-parametric/">non-parametric tests.</a></p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Analysis</th>
<th>Data type</th>
<th>Sensitivity to non-normality</th>
<th>Description</th>
<th>Use</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>PCA</td>
<td>Linear data</td>
<td>Sensitive</td>
<td>If you have continuous data with few zero values. Often strongly correlated variables</td>
<td>Genetic data, morphological data where you want to reduce complexity and the number of dimensions in the data</td>
</tr>
<tr class="even">
<td>CCA</td>
<td>Linear data</td>
<td>Less sensitive</td>
<td>Non-continuous data, many zero values, but <strong>data must be in the form of frequencies</strong> (number of individuals/cover degree)</td>
<td>Biodiversity analyses, correlation with environmental variables</td>
</tr>
<tr class="odd">
<td>NMDS</td>
<td>Non-linear data</td>
<td>Insensitive</td>
<td>Non-continuous data, many zero values and outlier data, or <strong>data that are not frequencies (for example presence/absence of a species)</strong></td>
<td>Biodiversity analyses, correlation with environmental variables</td>
</tr>
</tbody>
</table>
<p>As you can see, PCA is the analysis that demands the most of the data (normally distributed and continuous), while NMDS, a non-parametric method, can handle all kinds of data types, including data showing presence and absence (written as 1 and 0 in the dataset), but not exact numbers of individuals/cover degree. Because the method is robust and can handle all types of survey data, we will learn this method first.</p>
</section>
<section id="nmds---non-metric-multidimensional-scaling" class="level2">
<h2 class="anchored" data-anchor-id="nmds---non-metric-multidimensional-scaling">NMDS - Non-Metric Multidimensional Scaling</h2>
<p>As you can tell from the method’s name, NMDS is non-metric, meaning that the distance between species is not linear. For example, consider presence and absence of a species. If a species is absent, it simply isn’t there — but does the presence of blueberries in a plot mean there is an equal amount of blueberries in every plot where we have noted presence? No — it could be anything from a single small bush to a plot completely covered in blueberries.</p>
</section>
<section id="load-the-data" class="level2">
<h2 class="anchored" data-anchor-id="load-the-data">Load the data</h2>
<p>We have measured the cover degree of a number of plant species in quadrats in four habitats in forests around Umeå, and want to know whether the plant communities differ between the habitats.</p>
<p>Download the following file <a href="data/veg_umea.txt">veg_umea.txt</a> (right-click, choose “Save link as”) and save the file on your hard drive in a folder with a suitable name.</p>
<p>Continue by reading in the dataset and giving it a name — in this case we call it <code>veg_umea_data</code>. A detailed description of how to read in files can be found in our earlier tutorial <a href="https://martin-lind.github.io/Introduktion-till-R/tutorials/read-data/#l%C3%A4s-in-filen">Reading data into R</a>.</p>
<p><strong>Don’t forget to document your code in a script,</strong> with comments explaining what you are doing! <a href="https://martin-lind.github.io/Introduktion-till-R/tutorials/use-R/#anv%C3%A4nda-scriptfiler">See our tutorial on scripts</a> if you need a reminder of how to create and use scripts.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>veg_umea_data<span class="ot">&lt;-</span><span class="fu">read.table</span>(<span class="st">"data/veg_umea.txt"</span>,</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>                          <span class="at">header=</span>T,</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>                          <span class="at">sep=</span><span class="st">"</span><span class="sc">\t</span><span class="st">"</span>,</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>                          <span class="at">dec=</span><span class="st">","</span>) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="inspect-the-data" class="level3">
<h3 class="anchored" data-anchor-id="inspect-the-data">Inspect the data</h3>
<p>Start by looking at the structure of the data with <code>str()</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(veg_umea_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   42 obs. of  59 variables:
 $ habitat          : chr  "Meadow" "Meadow" "Meadow" "Meadow" ...
 $ moisture         : int  2 2 2 2 2 2 2 2 2 2 ...
 $ light            : int  3 3 3 3 3 3 3 3 3 3 ...
 $ nutrients        : int  3 3 3 3 3 3 3 3 3 3 ...
 $ angsfraken       : int  0 0 0 0 0 0 0 0 0 0 ...
 $ angsgroe         : int  0 0 25 5 0 25 0 0 0 0 ...
 $ angskovall       : int  0 0 0 0 0 0 0 0 0 5 ...
 $ angsyra          : int  0 0 0 0 0 0 5 5 0 0 ...
 $ Blabar           : int  0 0 0 0 0 0 0 0 5 0 ...
 $ Brudborste       : int  5 25 25 0 0 5 0 5 0 0 ...
 $ Brunror          : int  0 80 0 0 0 25 5 0 0 0 ...
 $ Dvarglummer      : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Ekbraken         : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Ekorrbar         : int  5 0 25 5 5 0 5 5 25 0 ...
 $ En               : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Fladervanderot   : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Gran             : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Grasstjarnblomma : int  0 0 5 5 0 0 0 0 0 0 ...
 $ Graal            : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Gullris          : int  0 0 0 0 5 0 0 0 5 5 ...
 $ Hallon           : int  0 0 0 5 0 0 0 0 0 0 ...
 $ Harsyra          : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Hasslebrodd      : int  5 0 0 0 0 0 0 0 0 0 ...
 $ Hultbraken       : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Karrviol         : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Krakbar          : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Krakvicker       : int  0 0 0 0 0 5 0 0 0 0 ...
 $ Krustatel        : int  0 0 80 0 25 0 80 0 80 25 ...
 $ Lingon           : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Ljung            : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Lundstjarnblomma : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Midsommarblomster: int  0 5 25 25 25 25 5 5 0 5 ...
 $ Mossviol         : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Mjolkort         : int  0 5 0 5 0 5 0 0 0 0 ...
 $ Nordbraken       : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Nordlundsarv     : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Nysort           : int  0 25 0 0 0 0 0 0 0 0 ...
 $ Ormbar           : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Odon             : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Revlummer        : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Rodblara         : int  0 5 5 5 5 25 5 5 0 5 ...
 $ Rodsvingel       : int  0 0 25 0 0 0 0 0 0 0 ...
 $ Rodven           : int  0 80 25 80 25 0 0 25 25 25 ...
 $ Rolleka          : int  0 5 80 25 0 5 0 0 5 0 ...
 $ Ronn             : int  0 0 0 0 0 0 0 0 5 0 ...
 $ Skogsbraken      : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Skogsfraken      : int  0 0 5 5 5 5 5 0 5 5 ...
 $ Skogskovall      : int  0 0 0 0 25 0 0 0 0 0 ...
 $ Skogsviol        : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Skogsstjarna     : int  5 0 5 5 5 0 5 0 5 0 ...
 $ Strutbraken      : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Sumpmara         : int  5 0 0 0 0 0 0 0 0 0 ...
 $ Topplosa         : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Trajon           : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Tuvtatel         : int  5 25 0 0 0 0 0 25 0 5 ...
 $ Varfryle         : int  0 0 0 25 25 80 25 5 25 0 ...
 $ akerbar          : int  0 5 0 0 0 0 0 0 0 0 ...
 $ Mossa            : int  0 80 80 80 80 25 80 5 80 80 ...
 $ Lav              : int  0 0 0 0 0 5 0 0 0 0 ...</code></pre>
</div>
</div>
<p>As you can see, the dataset is built with one column per species, while each row corresponds to a survey plot. If you run the code <code>head(veg_umea_data)</code> you will see that the dataset is full of zeros, meaning that species is absent from that plot. It is characteristic of biodiversity data that most species are absent from most plots (rare species only show up in one or a few plots), while only the very common species occur in many plots. This is why biodiversity data requires analyses that can handle many zero values (such as NMDS).</p>
</section>
</section>
<section id="create-a-community-matrix" class="level2">
<h2 class="anchored" data-anchor-id="create-a-community-matrix">Create a community matrix</h2>
<p>We continue by preparing our dataset for an NMDS analysis. The next step is to construct a <strong>community matrix</strong>, i.e.&nbsp;a matrix that contains all the species columns but no other columns (a matrix that contains the entire biological <em>community</em> we want to analyze). As we saw when we ran <code>str()</code>, the first four variables were names of treatments or environmental variables — it is only in column 5 that the first species appears. So we want to create a new dataset that starts at column 5 and continues to the last column.</p>
<p>To select columns from a dataset you can use the <code>[]</code> operator. We want to start with column number 5, but which is the last column? With the function <code>ncol()</code> we can find out the number of columns in our dataset.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ncol</span>(veg_umea_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 59</code></pre>
</div>
</div>
<p>We see that we have 59 columns, so our new dataset, which is a community matrix, should therefore span from column 5 to column 59 of our original data. We call our new dataset <code>community_matrix</code></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>community_matrix <span class="ot">&lt;-</span> veg_umea_data[,<span class="dv">5</span><span class="sc">:</span><span class="dv">59</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="run-an-nmds" class="level2">
<h2 class="anchored" data-anchor-id="run-an-nmds">Run an NMDS</h2>
<p>Now we have a community matrix, and we are ready to do an ordination! To do that, we start by loading the <code>vegan</code> package. If you haven’t installed it previously, first run the code <code>install.packages("vegan")</code> before loading the package.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(vegan)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: permute</code></pre>
</div>
</div>
<p>We use the function <code>metaMDS()</code>, where we specify our community matrix, how the distances should be calculated (the most suitable choice for species occurrence is Bray-Curtis, called <code>"bray"</code>), and finally the number of dimensions we want to visualize (normally we use 2 dimensions, specified with <code>k = 2</code>)</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>nmds_umea <span class="ot">&lt;-</span> <span class="fu">metaMDS</span>(community_matrix,</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">distance =</span> <span class="st">"bray"</span>,</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">k =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We run the code and get a number of lines starting with <code>Run...</code> — R is now analyzing your data through an iterative process where it searches for the best visualization of your data in two dimensions. It can happen in an instant or take longer, depending on the size of your community matrix.</p>
<p>Once it’s done, we choose to look at some information about our NMDS analysis, and we focus on the stress value.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>nmds_umea</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
metaMDS(comm = community_matrix, distance = "bray", k = 2) 

global Multidimensional Scaling using monoMDS

Data:     wisconsin(sqrt(community_matrix)) 
Distance: bray 

Dimensions: 2 
Stress:     0.146319 
Stress type 1, weak ties
Best solution was repeated 7 times in 20 tries
The best solution was from try 3 (random start)
Scaling: centring, PC rotation, halfchange scaling 
Species: expanded scores based on 'wisconsin(sqrt(community_matrix))' </code></pre>
</div>
</div>
<section id="stress-values" class="level3">
<h3 class="anchored" data-anchor-id="stress-values">Stress values</h3>
<p>When evaluating an NMDS you should focus on the stress value. We see the line <code>Stress: 0.146319</code>, which shows how well your community matrix can be represented in the number of dimensions you chose (in most cases 2 dimensions). The table below gives an indication of how to interpret your stress value.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 66%">
</colgroup>
<thead>
<tr class="header">
<th>Stress value</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>&lt; 0.05</td>
<td>Your NMDS is an excellent representation of your data</td>
</tr>
<tr class="even">
<td>&lt; 0.10</td>
<td>A good ordination, highly interpretable</td>
</tr>
<tr class="odd">
<td>&lt; 0.20</td>
<td>A usable ordination, but the details may be misleading — interpret with caution</td>
</tr>
<tr class="even">
<td>&gt; 0.35</td>
<td>Your ordination is essentially random and cannot be interpreted</td>
</tr>
</tbody>
</table>
<p>We have a stress value of 0.146, so the ordination is usable but should be interpreted with some caution. Note that the larger the dataset, the harder it is to visualize it in two dimensions, so you should not expect very low stress values in such cases.</p>
</section>
</section>
<section id="simple-figure" class="level2">
<h2 class="anchored" data-anchor-id="simple-figure">Simple figure</h2>
<p>We start with a simple figure of our NMDS analysis, without any specifications.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(nmds_umea)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We now get a graph in two dimensions. The two axes are NMDS1 (the axis explaining the most variation in your dataset) and NMDS2 (the axis perpendicular to NMDS1 that explains the second-most variation). The circles show the position of your survey plots, and the red crosses show the position of your species.</p>
<p>We see that the circles are not in the same place, meaning that our plots seem to have somewhat different plant communities. Likewise, the crosses are unevenly spread out, suggesting that species are not evenly distributed among the plots.</p>
<p>But we made our plots in four different habitats (forest types) — do they differ from each other? It’s hard to tell, since we don’t know which circles represent which habitats. So we need to keep working on the figure!</p>
</section>
<section id="complete-figure" class="level2">
<h2 class="anchored" data-anchor-id="complete-figure">Complete figure</h2>
<p>We choose to plot our four different habitats in different colors — if the circles representing a given habitat lie close together, separate from circles representing another habitat, we can interpret that as the habitats differing in plant community.</p>
<p>First we need to create a vector that associates each survey plot (site) with a vegetation type (i.e.&nbsp;a level of the variable <code>habitat</code>). Our habitats were in the first column of our dataset <code>veg_umea_data</code>; we select that column with the <code>[]</code> operator and save it in a new vector we call <code>habitats</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>habitats <span class="ot">&lt;-</span> veg_umea_data[,<span class="dv">1</span>]</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>habitats</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Meadow"        "Meadow"        "Meadow"        "Meadow"       
 [5] "Meadow"        "Meadow"        "Meadow"        "Meadow"       
 [9] "Meadow"        "Meadow"        "Stream"        "Stream"       
[13] "Stream"        "Stream"        "Stream"        "Stream"       
[17] "Stream"        "Stream"        "Stream"        "Stream"       
[21] "Stream"        "Spruce.forest" "Spruce.forest" "Spruce.forest"
[25] "Spruce.forest" "Spruce.forest" "Spruce.forest" "Spruce.forest"
[29] "Spruce.forest" "Spruce.forest" "Spruce.forest" "Pine.forest"  
[33] "Pine.forest"   "Pine.forest"   "Pine.forest"   "Pine.forest"  
[37] "Pine.forest"   "Pine.forest"   "Pine.forest"   "Pine.forest"  
[41] "Pine.forest"   "Pine.forest"  </code></pre>
</div>
</div>
<p>We see all four of our habitats listed. We also want the different habitats to have different colors, so we need to create a new variable with colors. We start by specifying a palette, i.e.&nbsp;which color each habitat should have. Feel free to choose colors that in some way symbolize your categories.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>my_palette <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Meadow"</span> <span class="ot">=</span> <span class="st">"green"</span>, </span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>                <span class="st">"Stream"</span> <span class="ot">=</span> <span class="st">"blue"</span>, </span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>                <span class="st">"Spruce.forest"</span> <span class="ot">=</span> <span class="st">"darkgreen"</span>, </span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>                <span class="st">"Pine.forest"</span> <span class="ot">=</span> <span class="st">"brown"</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>                )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Then we create the color vector <code>color_vector</code> with the function <code>match()</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>color_vector <span class="ot">&lt;-</span> my_palette[<span class="fu">match</span>(habitats, <span class="fu">names</span>(my_palette))]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>After that we convert habitat into a factor (which is required for later steps), while also making sure that the levels in habitat are directly linked to the colors, so the order isn’t lost (this can easily happen, since R likes to re-sort the order when converting a variable to a factor)</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>habitats <span class="ot">&lt;-</span> <span class="fu">factor</span>(habitats, <span class="at">levels =</span> <span class="fu">names</span>(my_palette))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Finally, we make a plot! We do it in several steps.</p>
<ol type="1">
<li><p>First we draw our ordination surface, but without any data illustrated on it (specified with <code>type = "n"</code>).</p></li>
<li><p>Then we add circles for the survey plots, giving them the colors from our <code>color_vector.</code></p></li>
<li><p>After that we add crosses for our species</p></li>
<li><p>Finally we add a legend. <code>"topleft"</code> means we place it in the upper left. Other choices include <code>"bottomleft"</code>, <code>"topright"</code>, and so on. Choose whichever fits your data best, so it doesn’t cover any points in the graph.</p></li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ordiplot</span>(nmds_umea, <span class="at">type=</span><span class="st">"n"</span>) <span class="co"># En tom plot (anges med type = "n")</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(nmds_umea, <span class="st">"sites"</span>, <span class="at">col =</span> color_vector, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">cex =</span> <span class="dv">1</span>) <span class="co"># Provytor</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(nmds_umea,<span class="st">"species"</span>, <span class="at">pch=</span><span class="dv">3</span>,<span class="at">col=</span><span class="st">"black"</span>) <span class="co"># Arter</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topleft"</span>,                    <span class="co"># Teckenförklaring</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">legend =</span> <span class="fu">names</span>(my_palette),</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">col =</span> my_palette,</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">pch =</span> <span class="dv">16</span>,</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Habitats"</span>,</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">bty =</span> <span class="st">"n"</span>) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We can also choose to draw ellipses around our habitats, specified with <code>ordiellipse()</code></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ordiplot</span>(nmds_umea, <span class="at">type =</span> <span class="st">"n"</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(nmds_umea, <span class="st">"sites"</span>, <span class="at">col =</span> color_vector, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">cex =</span> <span class="dv">1</span>) <span class="co"># Provytor</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(nmds_umea, <span class="st">"species"</span>, <span class="at">pch =</span> <span class="dv">3</span>, <span class="at">col =</span> <span class="st">"black"</span>) <span class="co"># Arter</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ordiellipse</span>(nmds_umea,                <span class="co"># Ellipser</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">groups =</span> habitats,</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>            <span class="at">col =</span> my_palette,</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>            <span class="at">kind =</span> <span class="st">"sd"</span>,      <span class="co"># eller "se"</span></span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>            <span class="at">lwd =</span> <span class="dv">2</span>,</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>            <span class="at">label =</span> <span class="cn">FALSE</span>)</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topleft"</span>,                    <span class="co"># Teckenförklaring</span></span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">legend =</span> <span class="fu">names</span>(my_palette),</span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">col =</span> my_palette,</span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>       <span class="at">pch =</span> <span class="dv">16</span>,</span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Habitats"</span>,</span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a>       <span class="at">bty =</span> <span class="st">"n"</span>) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Another option is to visualize the centroids (the center point of each habitat) and connect each point to its centroid. The advantage of this is that it directly corresponds to the statistical tests we will go through below, where we test whether our habitats differ.</p>
<p>First we extract our centroids from our ordination and save them in the vector <code>centroids</code></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>centroids <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(nmds_umea<span class="sc">$</span>points, <span class="at">by =</span> <span class="fu">list</span>(habitats), <span class="at">FUN =</span> mean)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Then we use this in our figure. We also choose to add lines from our centroids to our survey plots, using the function <code>ordispider()</code></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ordiplot</span>(nmds_umea, <span class="at">type =</span> <span class="st">"n"</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(nmds_umea, <span class="st">"sites"</span>, <span class="at">col =</span> color_vector, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">cex =</span> <span class="dv">1</span>) <span class="co"># Provytor</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(centroids[,<span class="dv">2</span><span class="sc">:</span><span class="dv">3</span>],<span class="co"># Centroider</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">pch =</span> <span class="dv">1</span>,        <span class="co"># symbol, välj något annat än dina sites</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">cex =</span> <span class="dv">2</span>,</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">lwd =</span> <span class="dv">2</span>,</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">col =</span> my_palette[centroids<span class="sc">$</span>Group<span class="fl">.1</span>])</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a><span class="fu">ordispider</span>(nmds_umea,           <span class="co"># Linjer från centroiden till dina provytor</span></span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>           <span class="at">groups =</span> habitats,</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>           <span class="at">col =</span> my_palette,</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>           <span class="at">lwd =</span> <span class="dv">1</span>)</span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(nmds_umea, <span class="st">"species"</span>, <span class="at">pch =</span> <span class="dv">3</span>, <span class="at">col =</span> <span class="st">"black"</span>) <span class="co"># Arter</span></span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topleft"</span>,                      <span class="co"># Teckenförklaring</span></span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a>       <span class="at">legend =</span> <span class="fu">names</span>(my_palette),</span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a>       <span class="at">col =</span> my_palette,</span>
<span id="cb21-21"><a href="#cb21-21" aria-hidden="true" tabindex="-1"></a>       <span class="at">pch =</span> <span class="dv">16</span>,</span>
<span id="cb21-22"><a href="#cb21-22" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Habitats"</span>,</span>
<span id="cb21-23"><a href="#cb21-23" aria-hidden="true" tabindex="-1"></a>       <span class="at">bty =</span> <span class="st">"n"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>As an alternative figure, we can choose to print some of the species names. We do that using the function <code>orditorp()</code>, where we specify that it is the species names we want to print.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ordiplot</span>(nmds_umea, <span class="at">type=</span><span class="st">"n"</span>) <span class="co"># En tom plot (anges med type = "n")</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(nmds_umea, <span class="st">"sites"</span>, <span class="at">col =</span> color_vector, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">cex =</span> <span class="dv">1</span>) <span class="co"># Provytor</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="fu">orditorp</span>(nmds_umea,<span class="at">display=</span><span class="st">"species"</span>, <span class="co"># Arter med artnamn</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">pch=</span><span class="dv">3</span>,</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">col=</span><span class="st">"black"</span>,</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">air=</span><span class="dv">2</span> <span class="co"># Justera air för att undvika överlappande artnamn. </span></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>         ) </span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topleft"</span>,                      <span class="co"># Teckenförklaring</span></span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">legend =</span> <span class="fu">names</span>(my_palette),</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">col =</span> my_palette,</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">pch =</span> <span class="dv">16</span>,</span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Habitats"</span>,</span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">bty =</span> <span class="st">"n"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><code>air</code> = specifies how much space there should be between the species names. If you set it to <code>air = 0</code>, species names are printed on top of one another, which can make everything unreadable if you have many species close together. Try different values of air until you find one that works well. Species that are not printed are shown with the species symbol <code>+</code>.</p>
<p>I think that in many cases it can be interesting to print out the species names, in order to see which species are specific to which communities. Note, however, that not all species are printed if you have a value of <code>air</code> higher than 0, so you cannot see the species that are not printed — they may be just as important as the ones that are printed. The reason they are not printed is that they lie so close to the other species names that they would cover them!</p>
<section id="what-should-be-included-in-the-graph" class="level3">
<h3 class="anchored" data-anchor-id="what-should-be-included-in-the-graph">What should be included in the graph?</h3>
<p>Which way of illustrating should you choose? It partly depends on what your dataset looks like, and how cluttered the graph becomes. Always include circles for survey plots, crosses for species, and a legend if you have more than one group of survey plots (different habitats, different treatments, or comparisons). Centroids are good to include if you are also running a statistical test on whether the groups differ in species composition, and ellipses <em>or</em> lines connecting the survey plots can improve understanding if the graph doesn’t become too cluttered.</p>
</section>
</section>
<section id="statistical-analysis---do-our-habitats-differ" class="level2">
<h2 class="anchored" data-anchor-id="statistical-analysis---do-our-habitats-differ">Statistical analysis - do our habitats differ?</h2>
<p>We can see in our ordination graph that it looks like our habitats differ in species composition. But can we test this statistically? Yes, that’s what we’ll look at now!</p>
<p>We use a technique called <strong>PERMANOVA</strong>. It is a multivariate ANOVA (i.e.&nbsp;a <strong>M</strong>ANOVA) that uses permutations (hence the name <strong>PER</strong>MANOVA). Permutations are a non-parametric type of test — the data is shuffled a large number of times, and each time a statistical test is performed. If your actual distribution of data is more extreme than what results from randomly reallocating your data among your groups, we can conclude that the result is not due to chance.</p>
<p>The null hypothesis in a PERMANOVA is that your groups do not differ in the position of their centroids and/or in the spread of the data (dispersion).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>m.habitats <span class="ot">&lt;-</span> <span class="fu">adonis2</span>(community_matrix <span class="sc">~</span> habitats, <span class="at">method =</span> <span class="st">"bray"</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>m.habitats</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Permutation test for adonis under reduced model
Permutation: free
Number of permutations: 999

adonis2(formula = community_matrix ~ habitats, method = "bray")
         Df SumOfSqs     R2      F Pr(&gt;F)    
Model     3   6.9658 0.5854 17.885  0.001 ***
Residual 38   4.9334 0.4146                  
Total    41  11.8992 1.0000                  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>We see that the p-value (called <code>Pr(&gt;F)</code>) is less than 0.05, i.e.&nbsp;we have a significant effect of habitat. Their centroids are therefore located in different places in the ordination.</p>
<section id="post-hoc-test-on-the-habitats" class="level3">
<h3 class="anchored" data-anchor-id="post-hoc-test-on-the-habitats">Post-hoc test on the habitats</h3>
<p>Since we have more than two habitats, we don’t yet know whether all of them differ from each other, or whether only one or a few do. We need to carry out a post-hoc test!</p>
<p>The simplest way is to use the package <code>pairwiseAdonis</code>, but unfortunately it needs to be installed manually via GitHub (<a href="https://github.com/pmartinezarbizu/pairwiseAdonis">see the description if you’re interested</a>). Therefore we’ll do it using the <code>vegan</code> package that we’re already using, even though it’s more cumbersome in terms of code. There’s quite a bit of code below, but the only thing we need to do is check how our variable <code>habitat</code> is written (lines 1, 4 and 6), as well as our community matrix (which we called <code>community_matrix</code>, line 6). That’s the only thing you might need to change in the code (unless you’ve given them different names than I have). The rest of the code should be left unchanged.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1"></a>pairs <span class="ot">&lt;-</span> <span class="fu">combn</span>(<span class="fu">unique</span>(habitats), <span class="dv">2</span>, <span class="at">simplify =</span> <span class="cn">FALSE</span>)</span>
<span id="cb25-2"><a href="#cb25-2"></a>pairwise_results <span class="ot">&lt;-</span> <span class="fu">do.call</span>(rbind, <span class="fu">lapply</span>(pairs, <span class="cf">function</span>(pair) {</span>
<span id="cb25-3"><a href="#cb25-3"></a>  </span>
<span id="cb25-4"><a href="#cb25-4"></a>  subset_idx <span class="ot">&lt;-</span> habitats <span class="sc">%in%</span> pair</span>
<span id="cb25-5"><a href="#cb25-5"></a>  </span>
<span id="cb25-6"><a href="#cb25-6"></a>  mod <span class="ot">&lt;-</span> <span class="fu">adonis2</span>(community_matrix[subset_idx, ] <span class="sc">~</span> habitats[subset_idx],</span>
<span id="cb25-7"><a href="#cb25-7"></a>                 <span class="at">method =</span> <span class="st">"bray"</span>,</span>
<span id="cb25-8"><a href="#cb25-8"></a>                 <span class="at">permutations =</span> <span class="dv">999</span>)</span>
<span id="cb25-9"><a href="#cb25-9"></a>  </span>
<span id="cb25-10"><a href="#cb25-10"></a>  <span class="fu">data.frame</span>(</span>
<span id="cb25-11"><a href="#cb25-11"></a>    <span class="at">group1 =</span> pair[<span class="dv">1</span>],</span>
<span id="cb25-12"><a href="#cb25-12"></a>    <span class="at">group2 =</span> pair[<span class="dv">2</span>],</span>
<span id="cb25-13"><a href="#cb25-13"></a>    <span class="at">F =</span> mod<span class="sc">$</span>F[<span class="dv">1</span>],</span>
<span id="cb25-14"><a href="#cb25-14"></a>    <span class="at">R2 =</span> mod<span class="sc">$</span>R2[<span class="dv">1</span>],</span>
<span id="cb25-15"><a href="#cb25-15"></a>    <span class="at">p =</span> mod<span class="sc">$</span><span class="st">`</span><span class="at">Pr(&gt;F)</span><span class="st">`</span>[<span class="dv">1</span>]</span>
<span id="cb25-16"><a href="#cb25-16"></a>  )</span>
<span id="cb25-17"><a href="#cb25-17"></a>}))</span>
<span id="cb25-18"><a href="#cb25-18"></a></span>
<span id="cb25-19"><a href="#cb25-19"></a>pairwise_results<span class="sc">$</span>p_adj <span class="ot">&lt;-</span> <span class="fu">p.adjust</span>(pairwise_results<span class="sc">$</span>p, <span class="at">method =</span> <span class="st">"BH"</span>)</span>
<span id="cb25-20"><a href="#cb25-20"></a>pairwise_results<span class="sc">$</span>contrast <span class="ot">&lt;-</span> <span class="fu">paste</span>(pairwise_results<span class="sc">$</span>group1,</span>
<span id="cb25-21"><a href="#cb25-21"></a>                                   <span class="st">"vs"</span>,</span>
<span id="cb25-22"><a href="#cb25-22"></a>                                   pairwise_results<span class="sc">$</span>group2)</span>
<span id="cb25-23"><a href="#cb25-23"></a>pairwise_results[, <span class="fu">c</span>(<span class="st">"contrast"</span>, <span class="st">"F"</span>, <span class="st">"R2"</span>, <span class="st">"p"</span>, <span class="st">"p_adj"</span>)]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                      contrast         F        R2     p p_adj
1             Meadow vs Stream  8.519836 0.3095889 0.001 0.001
2      Meadow vs Spruce.forest 11.589142 0.3916687 0.001 0.001
3        Meadow vs Pine.forest 17.695218 0.4822214 0.001 0.001
4      Stream vs Spruce.forest 21.942916 0.5359393 0.001 0.001
5        Stream vs Pine.forest 22.488844 0.5292882 0.001 0.001
6 Spruce.forest vs Pine.forest 39.070244 0.6728101 0.001 0.001</code></pre>
</div>
</div>
<p>We look at <code>p_adj</code>, which is the p-value adjusted for multiple testing (this is always done in post-hoc tests). We see that all p-values are less than 0.05, i.e.&nbsp;all habitats differ from each other in species composition!</p>
</section>
<section id="evaluate-your-model" class="level3">
<h3 class="anchored" data-anchor-id="evaluate-your-model">Evaluate your model</h3>
<p>A prerequisite for a PERMANOVA is that your groups do not differ in dispersion (i.e.&nbsp;how spread out they are in the ordination). If they do, the difference in your PERMANOVA might partly be due to differences in dispersion.</p>
<p>We test this easily with the function <code>betadisper()</code>. We provide our community matrix and our habitats. We save the result in an object we call <code>disp_habitat</code></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>disp_habitat <span class="ot">&lt;-</span> <span class="fu">betadisper</span>(<span class="fu">vegdist</span>(community_matrix), habitats)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>First we look at an ANOVA table of our dispersion, with the function <code>anova()</code></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(disp_habitat)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: Distances
          Df  Sum Sq  Mean Sq F value   Pr(&gt;F)   
Groups     3 0.49897 0.166322  5.8165 0.002254 **
Residuals 38 1.08660 0.028595                    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>We see that we have a significant difference in dispersion between our habitats. To find out which habitats differ in dispersion we run a post-hoc test with the function <code>TukeyHSD()</code></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(disp_habitat)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = distances ~ group, data = df)

$group
                                 diff         lwr         upr     p adj
Stream-Meadow             -0.03383843 -0.23232823  0.16465137 0.9676509
Spruce.forest-Meadow      -0.28245373 -0.48561451 -0.07929294 0.0033048
Pine.forest-Meadow        -0.15049719 -0.34898699  0.04799261 0.1926781
Spruce.forest-Stream      -0.24861530 -0.44710510 -0.05012550 0.0091456
Pine.forest-Stream        -0.11665877 -0.31036498  0.07704745 0.3809811
Pine.forest-Spruce.forest  0.13195653 -0.06653327  0.33044633 0.2956771</code></pre>
</div>
</div>
<p>We see that our significant p-values are in the contrasts <code>Spruce.forest-Meadow</code> and <code>Spruce.forest-Stream</code>. The differences we detect in species composition between these habitats may therefore partly be due to <code>Spruce.forest</code> having lower dispersion.</p>
</section>
</section>
<section id="environmental-variables" class="level2">
<h2 class="anchored" data-anchor-id="environmental-variables">Environmental variables</h2>
<p>We have also measured three environmental variables, namely moisture, light and nutrient content. How are they correlated with our communities?</p>
<p>We start by creating a dataset of our environmental variables. If you run the code <code>str(veg_umea_data)</code> again, you’ll see that columns 2-4 represent environmental variables. We select those variables with the <code>[]</code> operator and save them in a new dataset we call <code>environment_data</code></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>environment_data <span class="ot">&lt;-</span> veg_umea_data[,<span class="dv">2</span><span class="sc">:</span><span class="dv">4</span>]</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(environment_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "moisture"  "light"     "nutrients"</code></pre>
</div>
</div>
<p>We analyze … using the function <code>envfit()</code> and save the result in the object <code>m.environment</code></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>m.environment <span class="ot">&lt;-</span> <span class="fu">envfit</span>(nmds_umea <span class="sc">~</span> moisture <span class="sc">+</span> light <span class="sc">+</span> nutrients, </span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>                        <span class="at">data =</span> environment_data, </span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>                        <span class="at">permutations =</span> <span class="dv">999</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>To the left of <code>~</code> we write our ordination <code>nmds_umea</code>, and to the right we list our environmental variables <code>moisture + light + nutrients</code>. The dataset used is <code>environment_data</code>, and we always run 999 permutations.</p>
<p>We type the object’s name to look at the result</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>m.environment</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
***VECTORS

             NMDS1    NMDS2     r2 Pr(&gt;r)    
moisture  -0.35205 -0.93598 0.2785  0.002 ** 
light     -0.33755  0.94131 0.0276  0.570    
nutrients -0.99905 -0.04361 0.8377  0.001 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Permutation: free
Number of permutations: 999</code></pre>
</div>
</div>
<p>We see that <code>moisture</code> and <code>nutrients</code> are significantly associated with the plant communities’ composition, while <code>light</code> is not. Note that each variable is tested separately, so if several variables are correlated with each other, they may represent the same ecological gradient.</p>
<section id="figure-with-environmental-variables" class="level3">
<h3 class="anchored" data-anchor-id="figure-with-environmental-variables">Figure with environmental variables</h3>
<p>Let’s add the environmental variables to our figure, and only draw the significant ones.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ordiplot</span>(nmds_umea, <span class="at">type =</span> <span class="st">"n"</span>)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(nmds_umea, <span class="st">"sites"</span>, <span class="at">col =</span> color_vector, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">cex =</span> <span class="dv">1</span>)</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(nmds_umea, <span class="st">"species"</span>, <span class="at">pch =</span> <span class="dv">3</span>, <span class="at">col =</span> <span class="st">"black"</span>)</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ordiellipse</span>(nmds_umea,</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">groups =</span> habitats,</span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>            <span class="at">col =</span> my_palette,</span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>            <span class="at">kind =</span> <span class="st">"sd"</span>,      <span class="co"># or "se"</span></span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>            <span class="at">lwd =</span> <span class="dv">2</span>,</span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a>            <span class="at">label =</span> <span class="cn">FALSE</span>)</span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-14"><a href="#cb37-14" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topleft"</span>,</span>
<span id="cb37-15"><a href="#cb37-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">legend =</span> <span class="fu">names</span>(my_palette),</span>
<span id="cb37-16"><a href="#cb37-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">col =</span> my_palette,</span>
<span id="cb37-17"><a href="#cb37-17" aria-hidden="true" tabindex="-1"></a>       <span class="at">pch =</span> <span class="dv">16</span>,</span>
<span id="cb37-18"><a href="#cb37-18" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Habitats"</span>,</span>
<span id="cb37-19"><a href="#cb37-19" aria-hidden="true" tabindex="-1"></a>       <span class="at">bty =</span> <span class="st">"n"</span>)</span>
<span id="cb37-20"><a href="#cb37-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-21"><a href="#cb37-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-22"><a href="#cb37-22" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(m.environment, <span class="co"># Den nya koden som lägger till miljövariabler</span></span>
<span id="cb37-23"><a href="#cb37-23" aria-hidden="true" tabindex="-1"></a>     <span class="at">p.max =</span> <span class="fl">0.05</span>,  <span class="co"># Det maximala p-värdet för att miljövariabeln skall ritas ut</span></span>
<span id="cb37-24"><a href="#cb37-24" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">"red"</span>,</span>
<span id="cb37-25"><a href="#cb37-25" aria-hidden="true" tabindex="-1"></a>     <span class="at">cex =</span> <span class="fl">1.2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Now we can see how our environmental variables are associated with our ordination. As expected, the environments at the meadow and the stream are more nutrient-rich. It may seem surprising that the moisture vector points away from the stream sites, even though they were also fairly moist — but the spruce forest was also moist, and the meadow was a wet meadow. Even though moisture was significant, it had a much lower explanatory power (r2 = 0.28) than the environmental vector nutrients (r2 = 0.84).</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>