<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Ordinering med NMDS – Introduktion till R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-5b4ad623e5705c0698d39aec6f10cf02.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link href="../../site_libs/htmltools-fill-0.5.9/fill.css" rel="stylesheet">
<script src="../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<script src="../../site_libs/plotly-binding-4.12.0/plotly.js"></script>
<script src="../../site_libs/typedarray-0.1/typedarray.min.js"></script>
<script src="../../site_libs/jquery-3.5.1/jquery.min.js"></script>
<link href="../../site_libs/crosstalk-1.2.2/css/crosstalk.min.css" rel="stylesheet">
<script src="../../site_libs/crosstalk-1.2.2/js/crosstalk.min.js"></script>
<link href="../../site_libs/plotly-htmlwidgets-css-2.25.2/plotly-htmlwidgets.css" rel="stylesheet">
<script src="../../site_libs/plotly-main-2.25.2/plotly-latest.min.js"></script>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Introduktion till R</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Hem</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../tutorials/index.html"> 
<span class="menu-text">Tutorials</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">Om hemsidan</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#den-multivariata-ordinerings-analysen" id="toc-den-multivariata-ordinerings-analysen" class="nav-link active" data-scroll-target="#den-multivariata-ordinerings-analysen">Den multivariata ordinerings-analysen</a></li>
  <li><a href="#illustration-av-en-ordinering" id="toc-illustration-av-en-ordinering" class="nav-link" data-scroll-target="#illustration-av-en-ordinering">Illustration av en ordinering</a></li>
  <li><a href="#olika-multivariata-analyser" id="toc-olika-multivariata-analyser" class="nav-link" data-scroll-target="#olika-multivariata-analyser">Olika multivariata analyser</a></li>
  <li><a href="#nmds---non-metric-multidimensional-scaling" id="toc-nmds---non-metric-multidimensional-scaling" class="nav-link" data-scroll-target="#nmds---non-metric-multidimensional-scaling">NMDS - Non-Metric Multidimensional Scaling</a></li>
  <li><a href="#läs-in-data" id="toc-läs-in-data" class="nav-link" data-scroll-target="#läs-in-data">Läs in data</a>
  <ul class="collapse">
  <li><a href="#inspektera-data" id="toc-inspektera-data" class="nav-link" data-scroll-target="#inspektera-data">Inspektera data</a></li>
  </ul></li>
  <li><a href="#gör-en-community-matrix" id="toc-gör-en-community-matrix" class="nav-link" data-scroll-target="#gör-en-community-matrix">Gör en community matrix</a></li>
  <li><a href="#gör-en-nmds" id="toc-gör-en-nmds" class="nav-link" data-scroll-target="#gör-en-nmds">Gör en NMDS</a>
  <ul class="collapse">
  <li><a href="#stress-värden" id="toc-stress-värden" class="nav-link" data-scroll-target="#stress-värden">Stress-värden</a></li>
  </ul></li>
  <li><a href="#enkel-figur" id="toc-enkel-figur" class="nav-link" data-scroll-target="#enkel-figur">Enkel figur</a></li>
  <li><a href="#fullständig-figur" id="toc-fullständig-figur" class="nav-link" data-scroll-target="#fullständig-figur">Fullständig figur</a>
  <ul class="collapse">
  <li><a href="#vad-skall-vara-med-på-grafen" id="toc-vad-skall-vara-med-på-grafen" class="nav-link" data-scroll-target="#vad-skall-vara-med-på-grafen">Vad skall vara med på grafen?</a></li>
  </ul></li>
  <li><a href="#statistisk-analys---skiljer-sig-våra-habitat" id="toc-statistisk-analys---skiljer-sig-våra-habitat" class="nav-link" data-scroll-target="#statistisk-analys---skiljer-sig-våra-habitat">Statistisk analys - skiljer sig våra habitat?</a>
  <ul class="collapse">
  <li><a href="#post-hoc-test-på-habitaten" id="toc-post-hoc-test-på-habitaten" class="nav-link" data-scroll-target="#post-hoc-test-på-habitaten">Post-hoc test på habitaten</a></li>
  <li><a href="#utvärdera-din-modell" id="toc-utvärdera-din-modell" class="nav-link" data-scroll-target="#utvärdera-din-modell">Utvärdera din modell</a></li>
  </ul></li>
  <li><a href="#miljövariabler" id="toc-miljövariabler" class="nav-link" data-scroll-target="#miljövariabler">Miljövariabler</a>
  <ul class="collapse">
  <li><a href="#figur-med-miljövariabler" id="toc-figur-med-miljövariabler" class="nav-link" data-scroll-target="#figur-med-miljövariabler">Figur med miljövariabler</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Ordinering med NMDS</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Vi har tidigare alltid haft en responsvariebal i varje analys, det kan vara växtens höjd, antal ungar hos bofinken eller pH värdet i sjöarna. Man kallar sådana modeller för <strong>univariata</strong>, då de enbart har en beroende variabel (responsvariabel) per analys. Men ibland kanske man är intresserad av många responsvariabler? Säg att du har tittat på förekomsten av alla växtarter i två olika miljöer, och har hittat ett sjuttiotal arter. Du kan testa art för art om den skiljer sig i abundans mellan de två olika miljöerna, men det blir väldigt många univariata test. Kan man inte istället titta på om <strong>växtsamhället</strong> i helhet skiljer sig mellan de två olika miljöerna?</p>
<p>Det är sådana här frågor som <strong>multivariata metoder</strong> är användbara för, Multivarata netoder har fler än en beoroende variabel (reponsvariabel), där alla responsvariabler analyseras tillsammanans i samma analys.</p>
<p>Den vanligaste typen av multivariata metoder som ekologer använder sig av är <strong>ordinering</strong>. Metoden används i genetiken där man kan mäta genuttryck av tiotusentals gener och vill veta om genuttrycket skiljer sig åt mellan behandlingar, men även när man har mätt tiotals morfologiska egenskaper hos individer och vill se om de skiljer sig åt i form. Det vi skall fokusera på här är dock hur ordinering används inom analys av biodiversitetsdata. Det kan vara vilka arter du observerat vid inventeringar, men ett nytt forskningsfält som också använder liknande metoder är analys av mikrobiomdata samt metabarcoding-studier med eDNA.</p>
<section id="den-multivariata-ordinerings-analysen" class="level3">
<h3 class="anchored" data-anchor-id="den-multivariata-ordinerings-analysen">Den multivariata ordinerings-analysen</h3>
<p>Alla våra tidigare analyser har haft en responsvariabel, som vi ritat ut på y-axeln, och med vår prediktor på x-axeln har vi fått en graf i två dimensioner. Men hur gör vi om vi har ytterligare en responsvariabel? Kan vi ha ytterligare en axel? Ja, I princip kan vi det, om vi gör grafen i tre dimensioner (en 3D-graf). Men sedan blir det svårt, hur visualiserar man 4 dimensioner? Kan du föreställa dig det? Om vi har mätt abundans av 50 arter så får vi 50 axlar, det går inte ens att föreställa sig hur en sådan graf ser ut! Hur skall vi göra?</p>
<p>Det är här ordineringen kommer in. Alla dina datapunkter ligger i den multivarata rymden, som har lika många dimensioner som du har resppnsvariabler. Men ditt data ligger inte helt slumpmässigt i den här rymden. Om du exempelvis har mätt abundansen i replikerade kvadrater i en granskog och i en tallskog så kommer artsammansättningen i alla dina kvadrater i granskogen troligen påminna om varandra, och detsamma gäller i tallskogen. Det som den multivariata analysen gör är att den först söker efter den raka linjen genom din multivarata rymd som förklarar mest av variationen i ditt dataset, och det blir din första axel. Sedan letar den upp en linje som ligger vinkelrätt från din första axel och som förklarar mest av den kvarvarande variationen i din data. Det blir din andra axel. Nu har vi två axlar, vi kan göra en figur i två dimensioner.</p>
</section>
<section id="illustration-av-en-ordinering" class="level3">
<h3 class="anchored" data-anchor-id="illustration-av-en-ordinering">Illustration av en ordinering</h3>
<p>Figuren nedan visar multivariat data i 3 dimensioner (tänk tre arter kallade X, Y och Z), där varje prick motsvarar en kvadrat med ett visst antal individer av arterna X, Y och Z.</p>
<ol type="1">
<li><p>Grafen går att rotera med musen. Rotera den tills du ser dimensionen med mest variation, det borde bli din första axel.</p></li>
<li><p>Tryck sedan på “Lägg till Axel 1” - det är den första axeln av din ordinering, som förklarar mest variation</p></li>
<li><p>Lägg sedan till Axel 2 med motsvarande knapp, det är en axel som är vinkelrätt mot axel 1 och som förklarar näst mest variation.</p></li>
<li><p>Rotera figuren så att Axel 1 är vägrätt och Axel 2 är lodrätt. Det motsvarar din ordinering i 2 dimensioner!</p></li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div class="plotly html-widget html-fill-item" id="htmlwidget-bbbdcf888a2a729dbcc9" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-bbbdcf888a2a729dbcc9">{"x":{"visdat":{"10a5a3d0178e4":["function () ","plotlyVisDat"],"10a5a2ba7e006":["function () ","data"],"10a5a1a64c04e":["function () ","data"],"10a5a4c8d4e6b":["function () ","data"]},"cur_data":"10a5a4c8d4e6b","attrs":{"10a5a2ba7e006":{"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"x":{},"y":{},"z":{},"type":"scatter3d","mode":"markers","marker":{"size":3},"name":"Data","inherit":true},"10a5a1a64c04e":{"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"x":{},"y":{},"z":{},"type":"scatter3d","mode":"lines","line":{"width":6,"color":"red"},"name":"Axel 1","visible":false,"inherit":true},"10a5a4c8d4e6b":{"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"x":{},"y":{},"z":{},"type":"scatter3d","mode":"lines","line":{"width":6,"color":"blue"},"name":"Axel 2","visible":false,"inherit":true}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"updatemenus":[{"type":"buttons","direction":"right","x":0.10000000000000001,"y":1.1000000000000001,"buttons":[{"label":"Visa Data","method":"update","args":[{"visible":[true,false,false]}]},{"label":"Lägg till Axel 1","method":"update","args":[{"visible":[true,true,false]}]},{"label":"Lägg till Axel 2","method":"update","args":[{"visible":[true,true,true]}]}]}],"scene":{"camera":{"eye":{"x":-0.5,"y":1.8,"z":0.59999999999999998}},"xaxis":{"title":"x"},"yaxis":{"title":"y"},"zaxis":{"title":"z"}},"hovermode":"closest","showlegend":true},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"x":[-0.5604756465522126,-0.23017748948327998,1.558708314149124,0.070508391424575989,0.12928773516094624,1.7150649868832812,0.46091620598920241,-1.2650612346065337,-0.68685285189352596,-0.44566197009995812,1.2240817974394618,0.35981382705736381,0.40077145059405211,0.11068271594511968,-0.55584113475407493,1.7869131368030782,0.49785047822923945,-1.9666171566296382,0.70135590156368544,-0.47279140772793404,-1.0678237059868452,-0.21797491465829505,-1.0260044483072397,-0.72889122929114003,-0.6250392678492569,-1.6866933107424134,0.83778704449452468,0.15337311783651522,-1.1381369370119476,1.2538149210699268,0.42646422147681357,-0.29507148299227121,0.89512566104502245,0.87813348753304221,0.82158108163748722,0.688640254100091,0.55391765353758882,-0.061911710576721679,-0.30596266373991676,-0.38047100101238263,-0.6947069789205127,-0.20791727801959878,-1.2653963515682645,2.1689559653385126,1.2079619983049905,-1.1231085832033496,-0.40288483529907598,-0.46665535362321875,0.77996511833631788,-0.083369066471829248,0.25331851399475486,-0.028546755348703028,-0.042870457291316069,1.3686022840144578,-0.22577098565926762,1.5164706044295397,-1.5487528042302212,0.58461374963606905,0.12385424384461378,0.21594156874397266,0.37963948275988207,-0.50232345310930226,-0.3332073836694201,-1.0185753831070885,-1.0717912264755773,0.303528641404258,0.44820977862942618,0.053004226730504138,0.92226746787973757,2.0500846856271444,-0.49103116605653524,-2.3091688756408129,1.0057385244622568,-0.7092007625823924,-0.68800861646735789,1.0255713696966988,-0.28477300705100878,-1.2207177122545354,0.18130347974915023,-0.13889136243904462,0.0057641858998869339,0.38528040112633055,-0.37066003179240942,0.64437654851883319,-0.22048656181875062,0.33178196391569692,1.096839013149348,0.43518149083380292,-0.32593158553122681,1.148807618451094,0.99350385596211943,0.54839695950806977,0.23873173511144125,-0.62790607603937143,1.3606524485300073,-0.60025958714712668,2.1873329930165775,1.5326106261851893,-0.23570035910047693,-1.0264209003067806],"y":[-0.80358379909142053,-0.055700137008359241,1.1236207120881125,-0.11736458655920574,-0.37237909550375087,1.3495381271021649,-0.023719269937175935,-1.8460199559792954,-0.739595541658702,0.1029687284504166,0.69159195664737361,0.59183322275840777,-0.48832419366934032,0.060765189993826033,-0.18496930583152882,1.5801071905258199,0.45111847965786328,-1.893646729456399,0.13623254823415726,-0.8902975214848039,-0.7954356662394132,-0.64811723881903716,-1.0660822804961261,-0.71115907953203572,0.42189958833669816,-1.6753295994416599,0.78792292173804823,0.16167891905106757,-1.3914378666746225,0.96739789379414209,1.0634468063931253,-0.010305159854209656,0.73671698983248801,0.49125837385662141,-0.36935874546026792,1.1165808099871606,-0.28718591263233989,0.32044438697729,0.70978165361680823,-1.0263233812958057,-0.2048734154490548,-0.29743256711691307,-1.7983891608273557,0.97783094537993442,0.16560151185669569,-1.1639401276478312,-1.0531856607372108,-0.02936589641066123,1.6740265649318902,-0.71021049119505297,0.59652423493339279,0.36168371622149259,0.13180492364200597,0.59069352307306244,-0.24034309184274344,1.0729788159585085,-0.95750747677393711,0.28147162165694067,0.58757008841850134,-0.014537173888328786,0.83006731899757158,-0.92644726582047476,-0.89664352931459224,0.80565966098553143,-1.0658617752606778,0.39193670889376409,0.67685265992046517,-0.19948693146996843,0.99624499646059472,1.8245500121942586,-0.50051518666607497,-1.8146885837499926,0.78755719270057345,0.49686533944217659,-0.92107494131030054,0.27245896222002719,-0.20892420605526763,-0.82133379508205984,0.3633045232544117,-0.34029575630678854,-0.52705171826568598,0.93981690894580949,-0.4713532194107049,0.082744807488379479,-0.2945290339255488,0.16683762395828144,1.4324313553762988,0.39051383876564055,0.11628162416727927,0.66940008617474489,0.90202573956049625,0.27637461186103851,0.2382771521759387,-0.95000653982026795,0.43312119216001987,0.5183990226562819,2.0502208062494707,0.60045282013567958,-0.49414324562059192,-1.4138767625440798],"z":[1.0602424908931796,0.55782778457762294,0.3096954150999518,0.34206060129609439,-0.030812377727831519,0.21454760800320205,-0.15672753494936728,-0.37603326423923383,0.70390597021919266,-0.2807356661278243,0.4641859299393109,0.12420066150070552,0.96312092264049709,-0.22092011449797799,-0.71868335082359747,1.2572728774453881,-0.10699191323538199,-0.77674754444783622,-0.3083283731300509,-0.61166430857742404,-0.5822678927705921,0.39444062289982779,0.36174652946007713,0.20269628613183471,-0.62091815897326419,-0.31087280684640839,-0.16978158611418717,-0.3304261975840676,0.29068814098487294,-0.17110819690505147,0.87184505156670133,-0.1896039905227985,0.33381714688737302,-0.077574620760252011,0.23440381957518924,-0.64916218209872356,0.27165190637213271,0.082402031080684141,-0.20376365587431089,-0.2731067296448253,-0.68020245025254078,-0.26582822804615591,0.65484890738724977,0.22247688872240345,0.46477474840538735,0.73880865753213809,0.064025837907221023,-0.90443825979910786,-0.44461012794843924,0.41410860357504031,-0.24009944931752714,-0.4037166743156908,-0.23293532280248946,0.55234140865492076,0.75847182029610216,0.39205910135777533,0.053275588992829137,0.52324244614623561,-0.17116385235631384,-0.65411906490681415,-0.31975911309559046,-0.21816277337774589,0.12596658334043123,-0.1008862510157934,0.93040240625596171,0.80797383752588448,-0.045526390825898683,-0.79191550497257601,-0.032129697034181282,0.52228095069194191,0.32714547500527286,-0.12891387845327312,0.60875681912918855,-1.2012971580235829,0.35713969697608877,0.20776938796873007,0.0076921083717037264,-0.32668312901578245,0.19574376538350435,0.044980537085584221,-0.67273994036318219,0.27894311026614343,0.14908923410184466,0.16453901937379156,0.03718768479162967,0.18285901745459571,0.22919983424228541,0.92085967677595226,-0.30737546948253508,0.45761647531545235,0.81033614264745735,0.71837660788418289,0.62051427709311757,-0.3176850766033838,1.5516312317634124,-0.42229906490535646,1.4120261769868789,-0.089281875963464929,0.04088458731305783,0.5359098640944413],"type":"scatter3d","mode":"markers","marker":{"color":"rgba(31,119,180,1)","size":3,"line":{"color":"rgba(31,119,180,1)"}},"name":"Data","error_y":{"color":"rgba(31,119,180,1)"},"error_x":{"color":"rgba(31,119,180,1)"},"line":{"color":"rgba(31,119,180,1)"},"frame":null},{"x":[-2.3386246196584719,2.7991160313618506],"y":[-2.2677730223245716,2.5681240233375964],"z":[-1.1386885055046723,1.4810368862880472],"type":"scatter3d","mode":"lines","line":{"color":"red","width":6},"name":"Axel 1","visible":false,"marker":{"color":"rgba(255,127,14,1)","line":{"color":"rgba(255,127,14,1)"}},"error_y":{"color":"rgba(255,127,14,1)"},"error_x":{"color":"rgba(255,127,14,1)"},"frame":null},{"x":[-0.16366821621512928,0.36591649973577939],"y":[-0.81358949654674029,0.92090063465987926],"z":[2.1342491076420611,-2.1061513020094491],"type":"scatter3d","mode":"lines","line":{"color":"blue","width":6},"name":"Axel 2","visible":false,"marker":{"color":"rgba(44,160,44,1)","line":{"color":"rgba(44,160,44,1)"}},"error_y":{"color":"rgba(44,160,44,1)"},"error_x":{"color":"rgba(44,160,44,1)"},"frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<p>Namnet på de två axlarna döps beroende på vilken typ av ordinering du gjort (se nedan). Om man gör en PCA heter de PC1 och PC2, gör man en NMDS heter de NMDS1 och NMDS2 osv. Om man gör en parametrisk analys (såsom PCA) kan man få reda på hur mycket variation som förklaras av varje ny axel eller deras eigenvärde, medan man för icke-parametriska analyser istället tittar på analysens stress-värde (se nedan) för att veta om ditt multivariata dataset går bra att visualisera i två dimensioner.</p>
</section>
<section id="olika-multivariata-analyser" class="level3">
<h3 class="anchored" data-anchor-id="olika-multivariata-analyser">Olika multivariata analyser</h3>
<p>Nedan går vi igenom de vanligaste multivariata analysmetoderna. Val av metod beror framför allt på om man har väldigt många nollor i sitt dataset (vilket är vanligt om man inventerat arter, man får nollor om arter saknas i vissa provytor).</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Analys</th>
<th>Datatyp</th>
<th>Känslighet för icke-normalfördelning</th>
<th>Beskrivning</th>
<th>Användning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>PCA</td>
<td>Linjära data</td>
<td>Känslig</td>
<td>Om du har kontinuerliga data med få nollvärden. Ofta starkt korrelerade variablar</td>
<td>Genetiska data, morfologiska data där du vill reducera komplexiteten och antal dimensioner i datat</td>
</tr>
<tr class="even">
<td>CCA</td>
<td>Linjära data</td>
<td>Mindre känslig</td>
<td>Ej kontinuerliga data, många nollvärden, men <strong>data måste vara i frekvenser</strong> (antal individer/täckningsgrad)</td>
<td>Biodiversitetsanalyser, korrelation med miljövariabler</td>
</tr>
<tr class="odd">
<td>NMDS</td>
<td>Icke-linjära data</td>
<td>Okänslig</td>
<td>Ej kontinuerliga data, många nollvärden och avvikande data eller <strong>data som inte är frekvenser (till exempel närvaro/frånvaro av art)</strong></td>
<td>Biodiversitetsanalyser, korrelation med miljövariabler</td>
</tr>
</tbody>
</table>
<p>Som du ser är PCA den analysen som kräver mest av datat (normalfördelat och kontinuerligt) medan NMDS som är en icke-parametrisk metod kan hantera alla möjliga datatyper, inklusive data som visar på närvaro och frånvaro (skrivs som 1 och 0 i datasetet), men inte exakt antal individer/täckningsgrad. Eftersom metoden är robust och klarar alla typer av data från inventeringar kommer vi att först att lära oss den metoden.</p>
</section>
<section id="nmds---non-metric-multidimensional-scaling" class="level2">
<h2 class="anchored" data-anchor-id="nmds---non-metric-multidimensional-scaling">NMDS - Non-Metric Multidimensional Scaling</h2>
<p>Som hörs av medodens namn, är NMDS icke-metrisk, det vill säga att avståndet mellan arterna inte är linjärt. Till exempel kan vi tänka oss närvaro och frånvaro av en art. Om en art saknas så finns den inte, men betyder närvaro av blåbär i en ruta att det är lika många blåbär i alla rutor där vi noterat närvaro? Nä, det kan vara allt ifrån en liten buske till en ruta som är helt täckt av blåbär.</p>
</section>
<section id="läs-in-data" class="level2">
<h2 class="anchored" data-anchor-id="läs-in-data">Läs in data</h2>
<p>Vi har mätt täckningsgrad av ett antal växtarter i kvadrater i fyra habitat i skogar omkring Umeå, och undrar om växtsammhållerna skiljer sig åt mellan habitaten.</p>
<p>Ladda ner följande fil <a href="data/veg_umea.txt">veg_umea.txt</a> (högerklicka, välj “spara länk som”) och spara filen på din hårddisk i en mapp med ett lämpligt namn.</p>
<p>Fortsätt med att läsa in datasetet och ge det ett namn, i det här fallet kallar vi det <code>veg_umea_data</code> En detalerad beskrivning i hur man läser in filer finns i vår tidigare tutorial <a href="https://martin-lind.github.io/Introduktion-till-R/tutorials/read-data/#l%C3%A4s-in-filen">Läsa in data i R</a>.</p>
<p><strong>Glöm inte att dokumentera din kod i ett script,</strong> med kommentarer som förklarar vad du gör! <a href="https://martin-lind.github.io/Introduktion-till-R/tutorials/use-R/#anv%C3%A4nda-scriptfiler">Se vår tutorial om script</a> om du behöver påminnelse om hur man skapar och använder script.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>veg_umea_data<span class="ot">&lt;-</span><span class="fu">read.table</span>(<span class="st">"data/veg_umea.txt"</span>,</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>                          <span class="at">header=</span>T,</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>                          <span class="at">sep=</span><span class="st">"</span><span class="sc">\t</span><span class="st">"</span>,</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>                          <span class="at">dec=</span><span class="st">","</span>) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="inspektera-data" class="level3">
<h3 class="anchored" data-anchor-id="inspektera-data">Inspektera data</h3>
<p>Börja med att titta på datans struktur med <code>str()</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(veg_umea_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   42 obs. of  59 variables:
 $ habitat          : chr  "Meadow" "Meadow" "Meadow" "Meadow" ...
 $ moisture         : int  2 2 2 2 2 2 2 2 2 2 ...
 $ light            : int  3 3 3 3 3 3 3 3 3 3 ...
 $ nutrients        : int  3 3 3 3 3 3 3 3 3 3 ...
 $ angsfraken       : int  0 0 0 0 0 0 0 0 0 0 ...
 $ angsgroe         : int  0 0 25 5 0 25 0 0 0 0 ...
 $ angskovall       : int  0 0 0 0 0 0 0 0 0 5 ...
 $ angsyra          : int  0 0 0 0 0 0 5 5 0 0 ...
 $ Blabar           : int  0 0 0 0 0 0 0 0 5 0 ...
 $ Brudborste       : int  5 25 25 0 0 5 0 5 0 0 ...
 $ Brunror          : int  0 80 0 0 0 25 5 0 0 0 ...
 $ Dvarglummer      : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Ekbraken         : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Ekorrbar         : int  5 0 25 5 5 0 5 5 25 0 ...
 $ En               : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Fladervanderot   : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Gran             : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Grasstjarnblomma : int  0 0 5 5 0 0 0 0 0 0 ...
 $ Graal            : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Gullris          : int  0 0 0 0 5 0 0 0 5 5 ...
 $ Hallon           : int  0 0 0 5 0 0 0 0 0 0 ...
 $ Harsyra          : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Hasslebrodd      : int  5 0 0 0 0 0 0 0 0 0 ...
 $ Hultbraken       : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Karrviol         : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Krakbar          : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Krakvicker       : int  0 0 0 0 0 5 0 0 0 0 ...
 $ Krustatel        : int  0 0 80 0 25 0 80 0 80 25 ...
 $ Lingon           : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Ljung            : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Lundstjarnblomma : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Midsommarblomster: int  0 5 25 25 25 25 5 5 0 5 ...
 $ Mossviol         : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Mjolkort         : int  0 5 0 5 0 5 0 0 0 0 ...
 $ Nordbraken       : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Nordlundsarv     : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Nysort           : int  0 25 0 0 0 0 0 0 0 0 ...
 $ Ormbar           : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Odon             : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Revlummer        : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Rodblara         : int  0 5 5 5 5 25 5 5 0 5 ...
 $ Rodsvingel       : int  0 0 25 0 0 0 0 0 0 0 ...
 $ Rodven           : int  0 80 25 80 25 0 0 25 25 25 ...
 $ Rolleka          : int  0 5 80 25 0 5 0 0 5 0 ...
 $ Ronn             : int  0 0 0 0 0 0 0 0 5 0 ...
 $ Skogsbraken      : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Skogsfraken      : int  0 0 5 5 5 5 5 0 5 5 ...
 $ Skogskovall      : int  0 0 0 0 25 0 0 0 0 0 ...
 $ Skogsviol        : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Skogsstjarna     : int  5 0 5 5 5 0 5 0 5 0 ...
 $ Strutbraken      : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Sumpmara         : int  5 0 0 0 0 0 0 0 0 0 ...
 $ Topplosa         : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Trajon           : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Tuvtatel         : int  5 25 0 0 0 0 0 25 0 5 ...
 $ Varfryle         : int  0 0 0 25 25 80 25 5 25 0 ...
 $ akerbar          : int  0 5 0 0 0 0 0 0 0 0 ...
 $ Mossa            : int  0 80 80 80 80 25 80 5 80 80 ...
 $ Lav              : int  0 0 0 0 0 5 0 0 0 0 ...</code></pre>
</div>
</div>
</section>
</section>
<section id="gör-en-community-matrix" class="level2">
<h2 class="anchored" data-anchor-id="gör-en-community-matrix">Gör en community matrix</h2>
<p>Vi fortsätter med att förbereda vårt dataset för en NMDS-analys. Nästa steg är att konstruera en <strong>community matrix</strong>, dvs en matris som innehåller alla kolumner med arter, men inga andra kolumner (en matris som innehåller hela det biologiska <em>samhället</em> vi vill analysera). Som vi såg när vi körde <code>str()</code> så var de fyra första variablerna namn på behandlingarna eller miljövariabler, det är först i kolumn 5 som den första arten dyker upp. Vi vill alltså skapa ett nytt dataset, som börjar med kolumn 5 och fortsätter till den sista kolumnen.</p>
<p>För att välja ut kolumner ur ett dataset kan man använda operatorn <code>[]</code>. Vi vill börja med kolumn nummer 5, men vilken är den sista kolumnen? med funktionen <code>ncol()</code> kan vi ta reda på antalet kolumner i vårt dataset.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ncol</span>(veg_umea_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 59</code></pre>
</div>
</div>
<p>Vi ser att vi har 59 kolumner, och vårt nya dataset som är en community matrix skall därför sträcka sig från kolumn 5 till kolumn 59 av vårt originaldata. Vi kallar vårt nya dataset <code>community_matrix</code></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>community_matrix <span class="ot">&lt;-</span> veg_umea_data[,<span class="dv">5</span><span class="sc">:</span><span class="dv">59</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="gör-en-nmds" class="level2">
<h2 class="anchored" data-anchor-id="gör-en-nmds">Gör en NMDS</h2>
<p>Nu har vi en community matrix, och vi är redo att göra en ordinering! För att göra det börjar vi med att läsa in paketet <code>vegan</code>. Om du inte har installerat det sidan tidigare kör du först koden <code>install.packages("vegan")</code> innan du läser in paketet.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(vegan)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: permute</code></pre>
</div>
</div>
<p>Vi använder oss av funktionen <code>metaMDS()</code> där vi anger vår community matrix, hur distanserna skall beräknas (det lämpligaste för artförekomst är Bray-Curtis, vilket kallas <code>"bray"</code>) och slutligen antalet dimensioner vi vill visualisera (normalt sett använder vi oss av 2 dimensioner, anges med <code>k = 2</code>)</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>nmds_umea <span class="ot">&lt;-</span> <span class="fu">metaMDS</span>(community_matrix,</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">distance =</span> <span class="st">"bray"</span>,</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">k =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Vi kör koden, och får ett antal rader som börjar med <code>Run...</code> R analyserar nu ditt data genom en iterativ process där den söker efter den bästa visualiseringen av din data i två dimensioner. Det kan gå sekundsnabbt eller ta längre tid, beroende på storleken av din community matrix.</p>
<p>När vi är klara väljer vi att titta på lite information om vår NMDS-analys, och vi fokuserar på stress-värdet.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>nmds_umea</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
metaMDS(comm = community_matrix, distance = "bray", k = 2) 

global Multidimensional Scaling using monoMDS

Data:     wisconsin(sqrt(community_matrix)) 
Distance: bray 

Dimensions: 2 
Stress:     0.146319 
Stress type 1, weak ties
Best solution was repeated 7 times in 20 tries
The best solution was from try 3 (random start)
Scaling: centring, PC rotation, halfchange scaling 
Species: expanded scores based on 'wisconsin(sqrt(community_matrix))' </code></pre>
</div>
</div>
<section id="stress-värden" class="level3">
<h3 class="anchored" data-anchor-id="stress-värden">Stress-värden</h3>
<p>När man utvärderar en NMDS skall man fokusera på stress-värdet. Vi ser raden <code>Stress: 0.146319</code> som visar hur väl din community matrix kan representeras i de antal dimensionerna du valt (i de flesta fall 2 dimensioner). Följande tabell ger en indikation av hur du skall tolka ditt stress-värde.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 31%">
<col style="width: 68%">
</colgroup>
<thead>
<tr class="header">
<th>Stress-värde</th>
<th>Tolkning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>&lt; 0.05</td>
<td>Din NMDS är en excellent representation av dina data</td>
</tr>
<tr class="even">
<td>&lt; 0.10</td>
<td>En bra ordinering, mycket tolkningsbar</td>
</tr>
<tr class="odd">
<td>&lt; 0.20</td>
<td>En användbar ordinering, men detaljerna kan vara missvisande, tolka med försiktighet</td>
</tr>
<tr class="even">
<td>&gt; 0.35</td>
<td>Din ordinering är helt slumpmässig och går inte att tolka</td>
</tr>
</tbody>
</table>
<p>Vi har ett stress-värde på 0.146, så ordineringen är användbar men skall tolkas med viss försiktighet. Det skall noteras att ju större dataset man har, desto svårare är det att visualisera det i två dimensioner, så man skall inte förvänta sig väldigt låga stress-värden i sådana fall.</p>
</section>
</section>
<section id="enkel-figur" class="level2">
<h2 class="anchored" data-anchor-id="enkel-figur">Enkel figur</h2>
<p>Vi börjar med en enkel figur av vår nmds-analys, utan några specificeringar.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(nmds_umea)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Vi får nu en graf i två dimensioner. De två axlarna är NMDS1 (axeln som förklarar mest variation i ditt dataset) och NMDS2 (den axeln som ligger vinkelrätt mot NMDS1 och som förklarar näst mest variation). Cirklarna visar positionen av dina provytor, och de röda kryssen visar positionen av dina arter.</p>
<p>Vi ser att cirklarna inte ligger på samma ställe, vilket betyder att våra provytor verkar ha någorlunda olika växtsamhällen. Likaså är kryssen ojämnt spridda, vilket tyder på att arterna inte är jämt fördelade mellan provytorna.</p>
<p>Men vi hade gjort våra provytor i fyra olika habitat (skogstyper), skiljer de sig från varandra? Det är svårt att se, eftersom vi inte vet vilka cirklar som representerar vilka habitat. Vi behöver därmed arbeta vidare med figuren!</p>
</section>
<section id="fullständig-figur" class="level2">
<h2 class="anchored" data-anchor-id="fullständig-figur">Fullständig figur</h2>
<p>Vi väljer att rita ut våra fyra olika habitat i olika färg, om då cirklarna som representerar ett visst habitat ligger nära varandra, silkt från cirkalr som representerar ett annat habitat, kan vi tolka det som att habitaten skiljer sig åt i växtsamhälle.</p>
<p>Först behöver vi skapa en vektor som associerar varje provruta (site) med en vegetationstyp (dvs en nivå ur variabeln <code>habitat</code>). Våra habitat låg i den första kolumnen i vårt dataset <code>veg_umea_data</code>, vi väljer ut den kolumnen med operatorn <code>[]</code> och sparar i en ny vektor som vi kallar <code>habitats</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>habitats <span class="ot">&lt;-</span> veg_umea_data[,<span class="dv">1</span>]</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>habitats</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Meadow"        "Meadow"        "Meadow"        "Meadow"       
 [5] "Meadow"        "Meadow"        "Meadow"        "Meadow"       
 [9] "Meadow"        "Meadow"        "Stream"        "Stream"       
[13] "Stream"        "Stream"        "Stream"        "Stream"       
[17] "Stream"        "Stream"        "Stream"        "Stream"       
[21] "Stream"        "Spruce.forest" "Spruce.forest" "Spruce.forest"
[25] "Spruce.forest" "Spruce.forest" "Spruce.forest" "Spruce.forest"
[29] "Spruce.forest" "Spruce.forest" "Spruce.forest" "Pine.forest"  
[33] "Pine.forest"   "Pine.forest"   "Pine.forest"   "Pine.forest"  
[37] "Pine.forest"   "Pine.forest"   "Pine.forest"   "Pine.forest"  
[41] "Pine.forest"   "Pine.forest"  </code></pre>
</div>
</div>
<p>Xi ser alla våra fyra habitat listade.Vi vill även att de olika habitaten skall ha olika färg, så vi behöver skapa en ny variabel med färger. Vi börjar med att ange en palett, dvs vad varje habitat skall ha för färg. Välj gärna färger som på något sätt kan symbolisera dina kategorier.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>my_palette <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Meadow"</span> <span class="ot">=</span> <span class="st">"green"</span>, </span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>                <span class="st">"Stream"</span> <span class="ot">=</span> <span class="st">"blue"</span>, </span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>                <span class="st">"Spruce.forest"</span> <span class="ot">=</span> <span class="st">"darkgreen"</span>, </span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>                <span class="st">"Pine.forest"</span> <span class="ot">=</span> <span class="st">"brown"</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>                )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Sedan skapar vi färg-vektorn <code>color_vector</code> med funktionen <code>match()</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>color_vector <span class="ot">&lt;-</span> my_palette[<span class="fu">match</span>(habitats, <span class="fu">names</span>(my_palette))]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Efter det gör vi om habitat till en faktor (vilket krävs för senare steg) men samtidigt ser vi till att nivåerna i habitat är direkt kopplade till färgerna, så att inte ordningen av dem tappas bort (det är lätt hänt när R gärna sorterar om ordningen när den gör om en variabel till en faktor)</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>habitats <span class="ot">&lt;-</span> <span class="fu">factor</span>(habitats, <span class="at">levels =</span> <span class="fu">names</span>(my_palette))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Slutligen gör vi en plot! Vi gör den i flera steg.</p>
<ol type="1">
<li><p>Först ritar vi vår ordineringsyta, men utan några data illustrerade i den (anges med <code>type = "n"</code>).</p></li>
<li><p>Sedan lägger vi till cirklar får provytor, och ger dem färgerna från vår <code>color_vector.</code></p></li>
<li><p>Efter det lägger vi till kryss för våra arter</p></li>
<li><p>Slutligen lägger vi till en teckenförklaring. <code>"topleft"</code> betyder att vi lägger den längs upp till vänster. Andra val är exempelvis “<code>bottomleft"</code>, <code>"topright"</code> osv. Välj det som bäst passar dina data, så att den inte täcker några punkter i grafen.</p></li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ordiplot</span>(nmds_umea, <span class="at">type=</span><span class="st">"n"</span>) <span class="co"># En tom plot (anges med type = "n")</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(nmds_umea, <span class="st">"sites"</span>, <span class="at">col =</span> color_vector, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">cex =</span> <span class="dv">1</span>) <span class="co"># Provytor</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(nmds_umea,<span class="st">"species"</span>, <span class="at">pch=</span><span class="dv">3</span>,<span class="at">col=</span><span class="st">"black"</span>) <span class="co"># Arter</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topleft"</span>,                    <span class="co"># Teckenförklaring</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">legend =</span> <span class="fu">names</span>(my_palette),</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">col =</span> my_palette,</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">pch =</span> <span class="dv">16</span>,</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Habitats"</span>,</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">bty =</span> <span class="st">"n"</span>) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Vi kan även välja att göra ellipser runt våra habitat, anges med <code>ordiellipse()</code></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ordiplot</span>(nmds_umea, <span class="at">type =</span> <span class="st">"n"</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(nmds_umea, <span class="st">"sites"</span>, <span class="at">col =</span> color_vector, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">cex =</span> <span class="dv">1</span>) <span class="co"># Provytor</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(nmds_umea, <span class="st">"species"</span>, <span class="at">pch =</span> <span class="dv">3</span>, <span class="at">col =</span> <span class="st">"black"</span>) <span class="co"># Arter</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ordiellipse</span>(nmds_umea,                <span class="co"># Ellipser</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">groups =</span> habitats,</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>            <span class="at">col =</span> my_palette,</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>            <span class="at">kind =</span> <span class="st">"sd"</span>,      <span class="co"># eller "se"</span></span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>            <span class="at">lwd =</span> <span class="dv">2</span>,</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>            <span class="at">label =</span> <span class="cn">FALSE</span>)</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topleft"</span>,                    <span class="co"># Teckenförklaring</span></span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">legend =</span> <span class="fu">names</span>(my_palette),</span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">col =</span> my_palette,</span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>       <span class="at">pch =</span> <span class="dv">16</span>,</span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Habitats"</span>,</span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a>       <span class="at">bty =</span> <span class="st">"n"</span>) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Ytterligare ett alternativ är att visualisera centroiderna (centerpunktion i varje habitat) samt knyta ihop varje punkt med sin centroid. Fördelen med det här är att det direkt korresponderar med de statistiska testen som vi kommer att gå igenom nedan, där vi testar om våra habitat skiljer sig åt.</p>
<p>Först extraherar vi våra centroider från vår ordinering och sparar dem i vektorn <code>centroids</code></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>centroids <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(nmds_umea<span class="sc">$</span>points, <span class="at">by =</span> <span class="fu">list</span>(habitats), <span class="at">FUN =</span> mean)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Sedan använder vi det i vår figur. Vi väljer även att lägga till linjer från våra centroider till våra provytor, med hjälp av funktionen <code>ordispider()</code></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ordiplot</span>(nmds_umea, <span class="at">type =</span> <span class="st">"n"</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(nmds_umea, <span class="st">"sites"</span>, <span class="at">col =</span> color_vector, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">cex =</span> <span class="dv">1</span>) <span class="co"># Provytor</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(centroids[,<span class="dv">2</span><span class="sc">:</span><span class="dv">3</span>],<span class="co"># Centroider</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">pch =</span> <span class="dv">1</span>,        <span class="co"># symbol, välj något annat än dina sites</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">cex =</span> <span class="dv">2</span>,</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">lwd =</span> <span class="dv">2</span>,</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">col =</span> my_palette[centroids<span class="sc">$</span>Group<span class="fl">.1</span>])</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a><span class="fu">ordispider</span>(nmds_umea,           <span class="co"># Linjer från centroiden till dina provytor</span></span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>           <span class="at">groups =</span> habitats,</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>           <span class="at">col =</span> my_palette,</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>           <span class="at">lwd =</span> <span class="dv">1</span>)</span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(nmds_umea, <span class="st">"species"</span>, <span class="at">pch =</span> <span class="dv">3</span>, <span class="at">col =</span> <span class="st">"black"</span>) <span class="co"># Arter</span></span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topleft"</span>,                      <span class="co"># Teckenförklaring</span></span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a>       <span class="at">legend =</span> <span class="fu">names</span>(my_palette),</span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a>       <span class="at">col =</span> my_palette,</span>
<span id="cb21-21"><a href="#cb21-21" aria-hidden="true" tabindex="-1"></a>       <span class="at">pch =</span> <span class="dv">16</span>,</span>
<span id="cb21-22"><a href="#cb21-22" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Habitats"</span>,</span>
<span id="cb21-23"><a href="#cb21-23" aria-hidden="true" tabindex="-1"></a>       <span class="at">bty =</span> <span class="st">"n"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Vi kan som en alternativ figur välja att skriva ut vissa av artnamnen. Det gör vi genom att använda oss av funktionen <code>orditorp()</code>, där vi specificerar att det är artnamnen vi vill skriva ut.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ordiplot</span>(nmds_umea, <span class="at">type=</span><span class="st">"n"</span>) <span class="co"># En tom plot (anges med type = "n")</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(nmds_umea, <span class="st">"sites"</span>, <span class="at">col =</span> color_vector, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">cex =</span> <span class="dv">1</span>) <span class="co"># Provytor</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="fu">orditorp</span>(nmds_umea,<span class="at">display=</span><span class="st">"species"</span>, <span class="co"># Arter med artnamn</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">pch=</span><span class="dv">3</span>,</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">col=</span><span class="st">"black"</span>,</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">air=</span><span class="dv">2</span> <span class="co"># Justera air för att undvika överlappande artnamn. </span></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>         ) </span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topleft"</span>,                      <span class="co"># Teckenförklaring</span></span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">legend =</span> <span class="fu">names</span>(my_palette),</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">col =</span> my_palette,</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">pch =</span> <span class="dv">16</span>,</span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Habitats"</span>,</span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">bty =</span> <span class="st">"n"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><code>air</code> = specifiserar hur mycket luft det skall vara mellan artnamnen. Om man sätter den till <code>air = 0</code> så skrivs artnamn ovanpå varandra, vilket kan göra det hela oläsligt om man har många arter som följs åt. Testa olika värden på air tills du hittar ett som är lämpligt. Arter som inte skrivs ut visas med artsymbolen<code>+</code>.</p>
<p>Jag tycker att det i många fall kan vara intressant att skriva ut artnamnen, för att se vilka arter är specifika för vilka samhällen. Notera dock att alla arter inte skrivs ut om man har högre värden på <code>air</code> än 0, så man kan inte se de arter som inte skrivs ut, de kan dockl vara lika viktiga som de som skrivs ut. Anledningen till att de inte skrivs ut är ju för att de ligger så nära de andra artnamnen att de skulle täcka dem!</p>
<section id="vad-skall-vara-med-på-grafen" class="level3">
<h3 class="anchored" data-anchor-id="vad-skall-vara-med-på-grafen">Vad skall vara med på grafen?</h3>
<p>Vilket sätt att illustrera skall man välja? Det beror delvis hur ditt dataset ser ut, och hur rörig grafen blir. Ha alltid med cirklar för provytor, kryss för arter och en teckenförklaring om du har mer än en grupp av provytor (olika habitat, olika behandlingar eller jämförelser). Centroid är bra tt ha med om man även gör ett statistiskt test på om grupperna skiljer sig åt i artsammansättning, och ellipser *eller *linjer som binder ihop provytorna kan ge ökad förståelse om grafen inte blir för plottrig.</p>
</section>
</section>
<section id="statistisk-analys---skiljer-sig-våra-habitat" class="level2">
<h2 class="anchored" data-anchor-id="statistisk-analys---skiljer-sig-våra-habitat">Statistisk analys - skiljer sig våra habitat?</h2>
<p>Vi ser i vår ordineringsgraf att det ser ut som om våra habitat skiljer sig åt i artsammansättning. Men kan vi testa det statistiskt? Ja, det skall vi titta på nu!</p>
<p>Vi använder oss av en teknik som kallas <strong>PERMANOVA</strong>. Det är en multivartiat ANOVA (dvs en <strong>M</strong>ANOVA), som använder sig av permutationer (därav namnet <strong>PER</strong>MANOVA). Permutationer är ett icke-parametriskt typ av test - datat blandas om ett stort antal gånger och varje gång görs ett statistiskt test. Om dina fakltiska fördelning av data är mer extrem än vad det blir om man slumpmässigt omfördelar dina data mellan dina grupper kan vi dra slutsatsen att resultatet inte beror på slumpen.</p>
<p>Nollhypotesen i en PERMSANOVA är att dina grupper inte skiljer sig i centroidernas placering och/eller i datans utspridning (dispersion).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>m.habitats <span class="ot">&lt;-</span> <span class="fu">adonis2</span>(community_matrix <span class="sc">~</span> habitats, <span class="at">method =</span> <span class="st">"bray"</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>m.habitats</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Permutation test for adonis under reduced model
Permutation: free
Number of permutations: 999

adonis2(formula = community_matrix ~ habitats, method = "bray")
         Df SumOfSqs     R2      F Pr(&gt;F)    
Model     3   6.9658 0.5854 17.885  0.001 ***
Residual 38   4.9334 0.4146                  
Total    41  11.8992 1.0000                  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Vi ser att p-värdet (kallat <code>Pr(&gt;F)</code>) är mindre än 0.05, dvs vi har en signifikant effekt av habitat. Deras centroider ligger alltså på olika platser i ordineringen.</p>
<section id="post-hoc-test-på-habitaten" class="level3">
<h3 class="anchored" data-anchor-id="post-hoc-test-på-habitaten">Post-hoc test på habitaten</h3>
<p>Eftersom vi har fler än två habitat så vet vi dock inte om alla skiljer sig från varandra, eller om bara någon eller några gör det. Vi behöver genomföra ett post-hoc test!</p>
<p>Det enklaste sättet är att använda paketet <code>pairwiseAdonis</code>, men tyvärr behöver det installeras manuellt via Github (<a href="https://github.com/pmartinezarbizu/pairwiseAdonis">se beskrivning om du är intresserad</a>). Därför gör vi det med hjälp av paketet <code>vegan</code> som vi redan använder, även om det är mer omständigt rent kodmässigt. Det är en hel del kod nedan, men det enda vi behöver göra är att kontrollera vad vår variabel <code>habitat</code> är inskriven (rad 1, 4 och 6), liksom vår community matrix (som vi kallade <code>community_matrix</code>, rad 6). Det är det enda som du kan behöva ändra i koden (om du inte har gett dem samma namn som jag gjort). Resten av koden skall lämnas oförändrad.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1"></a>pairs <span class="ot">&lt;-</span> <span class="fu">combn</span>(<span class="fu">unique</span>(habitats), <span class="dv">2</span>, <span class="at">simplify =</span> <span class="cn">FALSE</span>)</span>
<span id="cb25-2"><a href="#cb25-2"></a>pairwise_results <span class="ot">&lt;-</span> <span class="fu">do.call</span>(rbind, <span class="fu">lapply</span>(pairs, <span class="cf">function</span>(pair) {</span>
<span id="cb25-3"><a href="#cb25-3"></a>  </span>
<span id="cb25-4"><a href="#cb25-4"></a>  subset_idx <span class="ot">&lt;-</span> habitats <span class="sc">%in%</span> pair</span>
<span id="cb25-5"><a href="#cb25-5"></a>  </span>
<span id="cb25-6"><a href="#cb25-6"></a>  mod <span class="ot">&lt;-</span> <span class="fu">adonis2</span>(community_matrix[subset_idx, ] <span class="sc">~</span> habitats[subset_idx],</span>
<span id="cb25-7"><a href="#cb25-7"></a>                 <span class="at">method =</span> <span class="st">"bray"</span>,</span>
<span id="cb25-8"><a href="#cb25-8"></a>                 <span class="at">permutations =</span> <span class="dv">999</span>)</span>
<span id="cb25-9"><a href="#cb25-9"></a>  </span>
<span id="cb25-10"><a href="#cb25-10"></a>  <span class="fu">data.frame</span>(</span>
<span id="cb25-11"><a href="#cb25-11"></a>    <span class="at">group1 =</span> pair[<span class="dv">1</span>],</span>
<span id="cb25-12"><a href="#cb25-12"></a>    <span class="at">group2 =</span> pair[<span class="dv">2</span>],</span>
<span id="cb25-13"><a href="#cb25-13"></a>    <span class="at">F =</span> mod<span class="sc">$</span>F[<span class="dv">1</span>],</span>
<span id="cb25-14"><a href="#cb25-14"></a>    <span class="at">R2 =</span> mod<span class="sc">$</span>R2[<span class="dv">1</span>],</span>
<span id="cb25-15"><a href="#cb25-15"></a>    <span class="at">p =</span> mod<span class="sc">$</span><span class="st">`</span><span class="at">Pr(&gt;F)</span><span class="st">`</span>[<span class="dv">1</span>]</span>
<span id="cb25-16"><a href="#cb25-16"></a>  )</span>
<span id="cb25-17"><a href="#cb25-17"></a>}))</span>
<span id="cb25-18"><a href="#cb25-18"></a></span>
<span id="cb25-19"><a href="#cb25-19"></a>pairwise_results<span class="sc">$</span>p_adj <span class="ot">&lt;-</span> <span class="fu">p.adjust</span>(pairwise_results<span class="sc">$</span>p, <span class="at">method =</span> <span class="st">"BH"</span>)</span>
<span id="cb25-20"><a href="#cb25-20"></a>pairwise_results<span class="sc">$</span>contrast <span class="ot">&lt;-</span> <span class="fu">paste</span>(pairwise_results<span class="sc">$</span>group1,</span>
<span id="cb25-21"><a href="#cb25-21"></a>                                   <span class="st">"vs"</span>,</span>
<span id="cb25-22"><a href="#cb25-22"></a>                                   pairwise_results<span class="sc">$</span>group2)</span>
<span id="cb25-23"><a href="#cb25-23"></a>pairwise_results[, <span class="fu">c</span>(<span class="st">"contrast"</span>, <span class="st">"F"</span>, <span class="st">"R2"</span>, <span class="st">"p"</span>, <span class="st">"p_adj"</span>)]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                      contrast         F        R2     p p_adj
1             Meadow vs Stream  8.519836 0.3095889 0.001 0.001
2      Meadow vs Spruce.forest 11.589142 0.3916687 0.001 0.001
3        Meadow vs Pine.forest 17.695218 0.4822214 0.001 0.001
4      Stream vs Spruce.forest 21.942916 0.5359393 0.001 0.001
5        Stream vs Pine.forest 22.488844 0.5292882 0.001 0.001
6 Spruce.forest vs Pine.forest 39.070244 0.6728101 0.001 0.001</code></pre>
</div>
</div>
<p>Vi tittar på <code>p_adj</code>, som är p-värdet som är justerat för multipla tester (det görs alltid i post-hoc test). Vi ser att alla p-värden är mindre än 0.05, dvs alla habitat är skilda från varandra i artsammansättning!</p>
</section>
<section id="utvärdera-din-modell" class="level3">
<h3 class="anchored" data-anchor-id="utvärdera-din-modell">Utvärdera din modell</h3>
<p>En förutsättning för en PERMANOVA är att dina grupper inte skiljer sig åt i dispersion (dvs hur utspridda de är i ordineringen). Om så är fallet kan skillnaden i din PERMANOVA delvis bero på olika dispersion.</p>
<p>Vi testar det enkelt med funktionen <code>betadisper()</code>. Vi anger vår community matrix och våra habitat. Vi sparar resultatet i ett objekt som vi kallar <code>disp_habitat</code></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>disp_habitat <span class="ot">&lt;-</span> <span class="fu">betadisper</span>(<span class="fu">vegdist</span>(community_matrix), habitats)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Först tittar vi på en ANOVA-tabell av vår dispersal, med funktionen <code>anova()</code></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(disp_habitat)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: Distances
          Df  Sum Sq  Mean Sq F value   Pr(&gt;F)   
Groups     3 0.49897 0.166322  5.8165 0.002254 **
Residuals 38 1.08660 0.028595                    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Vi ser att vi har signifikant skillnad i dispersion mellan våra habitat. FÖr att veta vilka habitat som skiljer sig i dispersion gör vi ett post-hoc test med funktionen <code>TukeyHSD()</code></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(disp_habitat)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = distances ~ group, data = df)

$group
                                 diff         lwr         upr     p adj
Stream-Meadow             -0.03383843 -0.23232823  0.16465137 0.9676509
Spruce.forest-Meadow      -0.28245373 -0.48561451 -0.07929294 0.0033048
Pine.forest-Meadow        -0.15049719 -0.34898699  0.04799261 0.1926781
Spruce.forest-Stream      -0.24861530 -0.44710510 -0.05012550 0.0091456
Pine.forest-Stream        -0.11665877 -0.31036498  0.07704745 0.3809811
Pine.forest-Spruce.forest  0.13195653 -0.06653327  0.33044633 0.2956771</code></pre>
</div>
</div>
<p>Vi ser att våra signifikanta p-värden är i kontrasterna <code>Spruce.forest-Meadow</code> samt <code>Spruce.forest-Stream</code>. De skillnaderna vi upptäcker i artsammansättning mellan dessa habitat kan alltså till viss del bero på att <code>Spruce.forest</code> har lägre dispersion.</p>
</section>
</section>
<section id="miljövariabler" class="level2">
<h2 class="anchored" data-anchor-id="miljövariabler">Miljövariabler</h2>
<p>Vi har även mätt tre miljövariabler, nämligen fuktighet, ljus och näringshalt. Hur är de korrelerade med våra samhällen?</p>
<p>Vi börjar med att skapa ett dataset av våra miljövariabler. Om du på nytt kör koden <code>str(veg_umea_data)</code> ser du att kolumn 2-4 representerar miljövariabler. Vi väljer ut de variablerna med operatorn <code>[]</code> och sparar i ett nytt dataset som vi kallar <code>environment_data</code></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>environment_data <span class="ot">&lt;-</span> veg_umea_data[,<span class="dv">2</span><span class="sc">:</span><span class="dv">4</span>]</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(environment_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "moisture"  "light"     "nutrients"</code></pre>
</div>
</div>
<p>Vi analyserar … med hjälp av funktionen <code>envfit()</code> och sparar resultatet i objektet <code>m.environment</code></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>m.environment <span class="ot">&lt;-</span> <span class="fu">envfit</span>(nmds_umea <span class="sc">~</span> moisture <span class="sc">+</span> light <span class="sc">+</span> nutrients, </span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>                        <span class="at">data =</span> environment_data, </span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>                        <span class="at">permutations =</span> <span class="dv">999</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Till vänster om <code>~</code>skriver vi ut vår ordinering <code>nmds_umea</code> och till höger har vi våra miljövariablar uppradade <code>moisture + light + nutrients</code>. Datasetet som används är <code>environment_data</code> och vi gör alltid 999 permuteringar.</p>
<p>Vi skriver in objektets namn för att titta på resultatet</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>m.environment</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
***VECTORS

             NMDS1    NMDS2     r2 Pr(&gt;r)    
moisture  -0.35205 -0.93598 0.2785  0.002 ** 
light     -0.33755  0.94131 0.0276  0.570    
nutrients -0.99905 -0.04361 0.8377  0.001 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Permutation: free
Number of permutations: 999</code></pre>
</div>
</div>
<p>Vi ser att <code>moisture</code> (fuktighet) och <code>nutrients</code> (näring) är signifikant associerat med växtsamhällernas komposition, medan <code>light</code> (ljus) inte är det. Notera att varje variabel är testad för sig, så om flera variabler korrelerar med varandra så kan de representera samma ekologiska gradient.</p>
<section id="figur-med-miljövariabler" class="level3">
<h3 class="anchored" data-anchor-id="figur-med-miljövariabler">Figur med miljövariabler</h3>
<p>Låt oss lägga till miljövariablerna i vår figur, och enbart rita ut de signifikanta variablerna.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ordiplot</span>(nmds_umea, <span class="at">type =</span> <span class="st">"n"</span>)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(nmds_umea, <span class="st">"sites"</span>, <span class="at">col =</span> color_vector, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">cex =</span> <span class="dv">1</span>)</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(nmds_umea, <span class="st">"species"</span>, <span class="at">pch =</span> <span class="dv">3</span>, <span class="at">col =</span> <span class="st">"black"</span>)</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ordiellipse</span>(nmds_umea,</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">groups =</span> habitats,</span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>            <span class="at">col =</span> my_palette,</span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>            <span class="at">kind =</span> <span class="st">"sd"</span>,      <span class="co"># or "se"</span></span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>            <span class="at">lwd =</span> <span class="dv">2</span>,</span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a>            <span class="at">label =</span> <span class="cn">FALSE</span>)</span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-14"><a href="#cb37-14" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topleft"</span>,</span>
<span id="cb37-15"><a href="#cb37-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">legend =</span> <span class="fu">names</span>(my_palette),</span>
<span id="cb37-16"><a href="#cb37-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">col =</span> my_palette,</span>
<span id="cb37-17"><a href="#cb37-17" aria-hidden="true" tabindex="-1"></a>       <span class="at">pch =</span> <span class="dv">16</span>,</span>
<span id="cb37-18"><a href="#cb37-18" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Habitats"</span>,</span>
<span id="cb37-19"><a href="#cb37-19" aria-hidden="true" tabindex="-1"></a>       <span class="at">bty =</span> <span class="st">"n"</span>)</span>
<span id="cb37-20"><a href="#cb37-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-21"><a href="#cb37-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-22"><a href="#cb37-22" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(m.environment, <span class="co"># Den nya koden som lägger till miljövariabler</span></span>
<span id="cb37-23"><a href="#cb37-23" aria-hidden="true" tabindex="-1"></a>     <span class="at">p.max =</span> <span class="fl">0.05</span>,  <span class="co"># Det maximala p-värdet för att miljövariabeln skall ritas ut</span></span>
<span id="cb37-24"><a href="#cb37-24" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">"red"</span>,</span>
<span id="cb37-25"><a href="#cb37-25" aria-hidden="true" tabindex="-1"></a>     <span class="at">cex =</span> <span class="fl">1.2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Nu ser vi hur våra miljövariabler är associerade med vår ordinering. SOm förväntat är miljöerna vid ängen och bäcken mer näringsrika. Det kan verka förvånande att vektorn för moisture går bort från lokalerna vid bäcken, trots att de också var ganska fuktiga, men även granskogen var fuktig och ängen var en fuktäng. Även om moisture var signifikant så hade den en myckel lägre förklaringsgrad (r2 = 0.28) än vad miljövektorn nutrients har (r2 = 0.84).</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>