---
title: "Tutorials"
---

## Lista över tutorials

### Att installera och arbeta i R

-   [Installera R](install-R/)
-   [Använda R, en introduktion](use-R)
-   [Installera paket](R-packages)
-   [Läsa in data i R](read-data/)

### Statistiska test - grundläggande

-   [t-test](t-test/) - jämföra medelvärden mellan två grupper
-   [Linjär regression](linear-regression/) - orsakssamband mellan två kontinuerliga variablar
-   [Korrelation](correlation/) - samband mellan två kontinuerliga variablar
-   [Envägs ANOVA](anova/) - jämföra medelvärden mellan fler än två grupper
-   [$\chi$ ^2^ test (Chi-2)](chi2/) - skiljer sig frekvenser åt mellan grupper i en korstabell
-   [Transformeringar](transformations/) - gör om skeva fördelningar till normalfördelning
-   [Icke-parametriska tester](non-parametric) - om data har omöjliga fördelningar
-   [Faktoriell (tvåvägs) ANOVA](factorial-anova/) - hur två kategoriska faktorer påverkar din respons
-   [Ancova](ancova) - skiljer sig två regressionslinjer åt i lutning och läge

### Manipulering av dataset

\[Innehåll planeras i framtiden\]

### Statistiska test - fortsättning

\[Innehåll planeras i framtiden\]

### Biodiversitets-analyser

\[Innehåll planeras i framtiden\]

-   [Ordinering med NMDS](nmds/) [under utveckling]
